(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"holterman_background_atlas_1", frames: [[0,0,2032,915]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.CachedBmp_1 = function() {
	this.initialize(ss["holterman_background_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#330000").ss(1,1,1).p("ApJEpQCEB1BqBsQCmCrAbAaQBsh7DEjyQDakNAvg4QCfi5CIjAQBHhlB9i1QAKgOAJgOAvWhBQHhirLljdQFThmB9goQDWhFBrgyQgoAghPA4QjWCVnzE/QqdGshtAfAvWhBQgRgNgPgMAwAgyQAUgHAWgIAqiDlQAAAHAAAHQgighgvg0QiIiUhbhLApSEhQAEAEAFAEQgJACgFAAQgRAAg6g4QABA7AJBtQAKB6AABCQBwhLCKgt");
	this.shape.setTransform(102.5,71.925);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(-1,-1,207,145.9), null);


(lib.smoke = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// smoke_animation
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#999999").s().p("AAoE5IgNgBIgXgDIgHgCIgJgDIgJgEIgIAEIgKADIgKACIgKACIgLABIgLgBIgKgDIgKgDIgKgEIgJgFIgEgCIgHgCIgIgDIgIgDIgIgEIgJgDIgJgEIgHgEIgJgHIgJgGIgJgHIgJgIIgFgHIgIgIIgGgIIgGgIIgGgJIgDgGIgEgGIgFgKIgHgKIgEgGIgDgIIgDgSIgDgSIAAgTIABgXIADgXIABgKIADgLIAEgJIADgIIAFgIIAFgHIAGgGIAGgIIAIgIIAIgIIgDgJIgCgJIgDgIIAAgKIAAgJIABgJIACgJIADgJIAFgHIAEgIIAGgIIAFgHIAGgHIAJgHIAJgHIADgLIAEgLIAEgKIAHgKIAFgIIAGgIIAHgIIAHgGIAJgHIAFgGIAFgHIAVgQIARgLIAUgMQAJgFALgEQAKgEAKgCQAPgDAOAAIALgEIAKgDIAMgCIALgCIAMgBIANgBIALABIAKACIAKACIAKADIAKAFIAIAGIAIAGIAIAGIAHAHIAFAHIAGAIIAGAJIADAJIAEAKIADAJIABACIAEAKIAFALIADAGIAFAFIAEAJIAGAJIAEAJQAJAXACAYQABATAAATIAAAmIAAAmQAAATgEAUIACAMIABANIABANIAAAJIAAAJIAAAJIAHAGIAGAHIAHAIIAEAJIAEAJIAEAKIAGAHIAFAIIAEAJIADAJIADAKIAAAKIAAAJIgCAJIgDAJIgDAIIgFAIIgFAHIgGAHIgGAFIgIAGIgHAEIgIAEIgJACIgJACIgJAAIgNAAIgNAAIgNAAIgHAGIgIAFIgJAEIgJAEIgJADIgWADIgYACIgQAAIgRAAg");
	this.shape.setTransform(0,0.025);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#999999").s().p("AApFGIgNgBIgYgDIgHgCIgKgEIgJgDIgIAEIgKADIgKACIgMACIgMABIgLgBIgJgDIgLgEIgKgEIgKgEIgEgDIgIgCIgIgDIgIgDIgIgFIgJgDIgKgDIgHgEIgJgIIgKgHIgKgHIgIgIIgGgHIgIgIQgEgEgDgFIgFgIIgGgKIgEgGIgEgGIgGgKIgGgLIgFgGIgDgJIgEgSIgCgTIgBgUIACgXIADgYIABgLIADgMIADgJIAFgIIAEgIIAGgIIAGgGIAGgIIAIgJIAJgIIgDgJIgDgKIgCgIIgBgKIAAgKIABgKIADgJIADgJIAFgIIAEgIIAHgIIAFgIIAGgHIAJgHIAKgHIACgMIAFgLIAEgLIAHgKIAGgIIAFgIIAHgJIAIgGIAJgHIAGgHIAFgHIAXgQIARgMIAUgMQALgGAKgEQALgEAKgCQAPgDAPgBIALgEIAMgDIALgCIAMgCIANgBIANgBIALABIALACIALACIAKADIAKAFIAJAHIAIAGIAIAGIAHAHIAGAIIAGAIIAFAJIAFAKIADAKIADAKIABACIAFALIAFALIADAGIAFAGIAFAIIAGAKIAEAKQAJAXACAaQABATAAAUIAAAnIAAAoQAAAUgEAUIACANIABAOIABANIAAAJIAAAKIAAAJIAIAGIAGAIIAGAIIAFAJIAEAKIAEAKIAGAIIAGAIIAEAKIAEAJIACAKIABALIgBAJIgCAKIgDAIIgDAJIgFAIIgFAIIgGAHIgHAFIgHAGIgIAFIgJADIgJADIgJACIgKAAIgOAAIgNAAIgOAAIgHAGIgJAGIgJADIgKAEIgIAEIgWADIgaACIgRAAIgSAAg");
	this.shape_1.setTransform(0,-13.275);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#999999").s().p("AArFTIgOgBIgYgDIgJgDIgJgDIgJgEIgJAEIgKADIgLADIgNACIgLAAIgLAAIgMgDIgKgEIgLgEIgKgGIgEgCIgHgCIgJgDIgIgDIgJgFIgJgEIgKgDIgIgFIgKgHIgKgHIgJgHIgKgIIgGgJIgIgIIgHgJIgHgJIgFgJIgEgHIgEgHIgHgKIgHgLIgEgHIgDgJIgEgTIgCgTIAAgVIAAgYIADgZIACgMIAEgLIADgKIAEgJIAFgIIAGgIIAGgHIAGgIIAJgJIAJgIIgDgKIgDgKIgDgJIAAgKIAAgKIABgKIADgKIACgJIAGgIIAFgJIAGgIIAGgIIAGgIIAJgHIAKgIIAEgMIADgLIAGgMIAGgKIAGgJIAHgIIAHgJIAHgGIALgHIAEgIIAGgHIAXgRIASgNIAWgMQAKgGALgEQALgEALgCQAQgDAQgBIALgEIAMgDIALgDIANgCIAOgBIANgBIAMABIALACIALACIALAEIAKAFIAIAGIAJAHIAJAHIAHAHIAHAHIAGAJIAFAKIAFAJIADAMIADAKIABACIAFALIAGALIADAGIAFAHIAFAJIAGAKIAFAKQAJAYACAbQABAUAAAUIAAAqIAAApQAAAVgEAVIACAOIABANIABAOIAAAKIAAAKIAAAJIAIAHIAHAIIAGAIIAFAKIAEAKIAFALIAGAIIAGAIIAEAKIAEAKIACAKIAAALIAAAKIgBAJIgDAKIgEAJIgFAIIgGAIIgGAHIgHAHIgIAFIgIAFIgJAEIgJADIgKACIgKAAIgOAAIgOAAIgOAAIgIAHIgJAEIgJAFIgKAEIgJAEIgYADIgaABIgSABIgSAAg");
	this.shape_2.setTransform(0,-26.55);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#999999").s().p("AAtFgIgPgBIgZgEIgJgCIgKgDIgJgFIgKAFIgKADIgMACIgMADIgMABIgMgBIgLgEIgMgDIgKgFIgLgFIgEgDIgIgCIgJgDIgIgEIgJgEIgLgDIgKgFIgIgEIgKgIIgKgHIgKgIIgKgJIgHgIIgHgJIgIgJQgEgEgCgFIgHgKIgDgHIgEgGIgHgLIgHgMIgFgHIgDgJIgEgUIgCgTIgBgXIABgZIADgZIACgNIAEgMIADgKIAEgJIAFgJIAHgIIAGgHIAGgIIAJgKIAKgIIgDgKIgEgLIgCgJIgBgKIAAgKIACgMIACgKIADgJIAFgJIAGgJIAGgIIAGgJIAHgHIAJgIIALgIIADgNIAEgMIAFgLIAHgKIAGgJIAHgJIAHgJIAJgIIAKgHIAFgIIAGgHIAYgSIATgNIAWgMQALgGALgFQAMgEALgCQARgEAQgBIAMgEIALgDIANgDIANgBIAOgCIAOgBIALACIAMABIAMACIALAEIALAFIAJAHIAJAHIAJAHIAHAHIAHAIIAGAJIAGAKIAFALIADALIADALIABABIAGAMIAFANIAEAGIAEAGIAGAJIAGAKIAFAMQAKAYABAcQACAVAAAVIAAArIAAArQAAAWgEAWIACANIABAQIABANIAAAKIAAALIAAAKIAIAGIAHAIIAHAJIAFAKIAFALIAEALIAHAIIAFAJIAFALIAEAJIACALIABAMIgBAKIgCAKIgDAKIgDAJIgFAJIgHAIIgGAIIgHAFIgIAHIgJAFIgJAEIgKACIgKACIgKABIgPAAIgOAAIgPAAIgIAGIgJAGIgKAEIgKAFIgKADIgYAEIgbACIgTAAIgSAAg");
	this.shape_3.setTransform(0.025,-39.85);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#999999").s().p("AAvFtIgQgBIgagEIgJgCIgKgEIgKgEIgKAEIgLAEQgGACgGAAIgMACIgNABIgMgBIgMgDIgMgEIgLgEIgKgGIgFgDIgJgCIgJgDIgIgEIgKgFIgKgDIgLgEIgIgFIgLgIIgKgIIgKgIIgKgJIgHgIIgIgJIgIgKIgHgJIgGgLIgFgHIgDgGIgHgMIgIgMIgEgHIgEgKIgEgUIgDgUIAAgYIABgaIADgbIACgLIAEgOIAEgKIADgJIAGgJIAHgJIAGgHIAHgJIAJgKIAKgIIgDgLIgEgKIgCgKIgBgLIAAgKIABgMIADgKIADgKIAGgJIAFgJIAHgJIAGgJIAHgIIAKgIIALgIIACgNIAFgMIAFgNIAIgLIAGgJIAHgJIAHgJIAJgIIAKgIIAGgHIAGgHIAZgUIAUgNIAWgNQAMgGAMgFQAMgEALgCQASgEAQgBIANgEIAMgEIAMgCIAOgCIAOgBIAPgCIAMACIANACIALACIAMADIALAGIAKAIIAJAHIAJAGIAIAIIAGAIIAHAKIAHAKIAEALIAEAMIADAKIABACIAGANIAFAMIAEAHIAFAGIAGAKIAGALIAFAKQAKAbACAcQABAWABAWIAAAtIAAAsQAAAXgFAWIACAPIACAPIAAAPIABAKIAAAKIAAALIAIAHIAHAIIAHAJIAGALIAEALIAFALIAHAJIAFAJIAGALIADAKIADALIAAANIAAAKIgDAKIgCAKIgEAKIgGAJIgGAIIgGAIIgIAHIgIAGIgJAFIgKAEIgKAEIgLABIgKAAIgPAAIgPAAIgPAAIgIAIIgKAFIgLAFIgKAEIgKAEIgZADIgcACIgTABIgTAAg");
	this.shape_4.setTransform(0,-53.15);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#999999").s().p("AAwF6IgQgBIgbgEIgJgCIgKgFIgLgEIgKAFIgMAEIgLACIgOACIgNABIgMgBIgNgDIgLgEIgMgFIgMgGIgEgDIgIgCIgKgDIgJgEIgJgFIgLgEIgMgEIgJgFIgKgIIgLgIIgLgJIgKgJIgHgJIgIgJQgFgEgEgFIgHgLIgGgKIgFgIIgDgHIgIgLIgHgMIgGgIIgDgKIgEgWIgDgVIAAgXIABgbIADgcIACgNIAEgNIAEgLIAEgKIAGgJIAHgJIAGgHIAHgJIAKgKIAKgJIgDgLIgEgLIgDgKIAAgMIAAgLIABgLIADgLIADgKIAGgJIAFgKIAHgJIAHgJIAHgJIAKgIIAMgIIACgOIAFgNIAFgMIAIgMIAHgJIAHgKIAIgKIAJgHIALgIIAFgIIAGgIIAagTIAUgOIAYgOQALgGANgFQAMgFAMgCQASgEARAAIANgFIANgEIANgCIAOgCIAPgCIAPgBIANACIAMACIANACIAMAEIALAGIAJAHIAKAHIAKAIIAHAIIAIAIIAHAKIAGALIAFALIAEAMIADALIABACIAHANIAEANIAFAHIAFAGIAGALIAHAKIAFAMQAKAbACAeQABAWABAXIAAAuIAAAuQAAAXgFAYIACAPIACAQIAAAPIABAKIAAALIAAALIAIAHIAIAJIAHAKIAFAKIAFAMIAFALIAHAJIAHAKIAEALIAEALIADAMIAAAMIAAALIgCALIgDAKIgEAKIgGAJIgHAJIgGAIIgIAHIgJAGIgJAGIgKAEIgKADIgLACIgLAAIgQAAIgPAAIgPAAIgJAIIgKAGIgLAEIgLAFIgKAEIgaADIgeACIgTABIgUAAg");
	this.shape_5.setTransform(0,-66.425);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#999999").s().p("AAxGHIgQgBIgcgEIgJgDIgLgEIgKgEIgLAFIgMADQgGACgGABIgOACIgNABIgOgBIgMgDIgNgFIgMgFIgLgFIgFgDIgJgDIgKgDIgJgEIgKgFIgLgEIgLgEIgJgFIgMgJIgLgIIgLgJIgKgJIgIgKIgJgJIgIgKIgIgLIgGgLIgEgHIgFgIIgHgMIgIgMIgGgIIgDgKIgFgXIgCgWIAAgYIABgcIADgdIACgNIAEgNIAEgMIAEgKIAHgJIAGgJIAHgIIAHgKIAKgKIALgJIgEgMIgEgLIgCgLIgBgLIAAgMIABgLIADgMIAEgKIAGgKIAFgKIAHgJIAIgJIAHgJIALgJIALgJIADgNIAFgOIAGgMIAHgMIAHgKIAHgKIAJgKIAJgIIALgIIAGgJIAHgIIAagUIAVgOIAZgOQALgHANgFQANgFAMgCQASgEATAAIANgFIANgEIAOgDIAOgCIAQgBIAPgCIANACIANACIANADIAMADIAMAHIAKAHIAKAIIAKAHIAIAJIAIAIIAHAKIAGAMIAFALIAEAMIAEAMIABACIAGANIAFAOIAFAHIAFAHIAGAKIAHALIAFAMQALAcACAfQACAXAAAYIAAAvIAAAwQAAAYgFAYIADAQIABAQIAAAQIABALIAAALIAAAMIAJAHIAIAJIAHAKIAFALIAGAMIAEAMIAIAJIAGAKIAFALIAFAMIACAMIAAAMIAAAMIgCALIgDALIgEAKIgGAJIgHAKIgGAIIgJAHIgJAHIgJAFIgLAFIgKADIgMACIgLAAIgQAAIgQAAIgQAAIgJAIIgKAGIgMAEIgLAFIgKAFIgbADIgeACIgVABIgVAAg");
	this.shape_6.setTransform(0,-79.725);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#999999").s().p("AAzGUIgRgBIgcgEIgKgDIgLgEIgMgFIgLAFIgLAEIgOADIgNACIgPABIgNgBIgNgEIgNgEIgMgFIgMgGIgFgDIgJgDIgKgDIgKgEIgLgGIgLgEIgLgEIgKgFIgMgJIgLgJIgLgJIgLgJIgIgKIgJgKIgIgKIgIgLIgHgMIgEgHIgFgIIgIgMIgIgNIgFgIIgEgLIgFgXIgCgXIgBgZIACgdIADgdIABgOIAFgOIAEgMIAFgKIAGgKIAHgJIAHgIIAIgKIAKgLIALgKIgEgLIgEgMIgDgLIAAgMIAAgMIABgMIADgLIAEgLIAGgKIAGgKIAHgKIAHgKIAIgJIALgJIALgJIAEgOQABgHADgHIAHgNIAIgMIAGgLIAIgKIAIgKIAKgJIAMgIIAGgIIAGgJIAcgUIAVgPIAagPQAMgHANgFQANgFANgCQATgEATgBIAOgFIANgEIAOgCIAOgDIARgBIAQgCIAOACIAMACIAOADIANAEIAMAGIAKAIIALAIIAKAHIAJAJIAHAJIAHALQAEAFADAGIAFAMIAEANIAEAMIABACIAGAOIAHAOIAEAHIAFAHIAHALIAHALIAFANQALAdACAfQACAYAAAZIAAAxIAAAxQAAAZgFAZIADAQIABARIAAAQIABAMIAAALIAAAMIAJAIIAIAJIAIAKIAFAMIAGAMIAFAMIAHAKIAHAKIAGAMIADALIADANIABANIgBAMIgCALIgDALIgFALIgFAKIgHAJIgIAJIgIAHIgJAHIgKAGIgLAEIgKAEIgMACIgMAAIgRAAIgQAAIgRAAIgJAIIgLAGIgLAFIgLAFIgMAEIgbAEIgfACIgVABIgWAAg");
	this.shape_7.setTransform(0,-93.025);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#999999").s().p("AA1GhIgSgBIgdgFIgKgCIgMgFIgMgEIgLAEIgMAFIgOACIgOACIgPABIgOgBIgNgDIgNgFIgNgFIgMgGIgFgDIgKgDIgKgDIgKgFIgKgFIgNgEIgMgFIgJgFIgMgKIgMgIIgMgKIgLgKIgIgKIgJgKIgJgKIgIgLIgHgNIgEgIIgGgHIgHgNIgJgNIgFgJIgEgKIgEgYIgEgYIAAgaIACgeIADgeIABgOIAFgOIAEgNIAFgLIAGgJIAHgKIAIgIIAIgKIAKgMIALgKIgDgMIgEgMIgDgLIgBgNIAAgLIACgOIACgLIAFgLIAGgKIAGgMIAHgJIAIgKIAIgKIAKgJIANgJIAEgPIAEgOIAGgOIAJgMIAHgLIAIgKIAJgMIAKgIIALgJIAHgIIAGgJIAdgVIAWgQIAagOQAMgIAPgFQANgFANgCQAUgFATgBIAOgFIAOgEIAOgCIAQgDIARgCIAQgBIAOACIANADIAOACIANAEIANAGIAKAJIALAIIALAIIAIAJIAIAJIAHALIAIAMIAFAMIAFANIADAMIABADIAHANIAGAQIAEAHIAGAHIAHAMIAHALIAGANQALAeACAgQACAZAAAZIAAAzIAAAzQAAAZgFAaIADARIABASIABAQIAAAMIAAAMIAAAMIAJAIIAJAKIAIAKIAFAMIAGANIAFAMIAIAKIAHALIAGAMIADAMIAEANIAAAOIAAALIgDANIgDALIgFALIgFAKIgIAKIgHAIIgJAIIgKAHIgKAGIgKAFIgMADIgMACIgLABIgSAAIgRAAIgSAAIgJAIIgKAGIgMAFIgNAFIgLAFIgcADIghADIgVABIgWAAg");
	this.shape_8.setTransform(0,-106.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#999999").s().p("AA2GtIgRgBIgfgEIgLgDIgMgEIgLgFIgMAFIgNAEIgOADIgPACIgPABIgOgBIgNgDIgOgFIgNgGIgNgFIgFgEIgKgDIgLgDIgKgFIgLgFIgMgFIgNgEIgKgGIgMgJIgMgJIgMgKIgMgKIgIgKIgKgLIgJgLIgIgLIgHgNIgFgIIgFgIIgIgNIgJgOIgFgJIgEgLIgFgYIgDgZIAAgbIABgeIADggIACgOIAFgPIAEgMIAFgMIAHgKIAHgKIAIgJIAIgKIALgLIALgLIgEgMIgEgMIgCgNIgBgMIAAgMIABgOIADgMIAEgMIAGgKIAHgLIAHgKIAIgKIAIgKIAMgJIANgKIADgPIAFgQIAGgNIAJgNIAHgLIAIgLIAJgLIAKgJIANgJIAGgJIAHgIIAegXIAXgQQANgIANgHQANgHAOgGQAOgFAOgDQAUgEAUAAIAPgGIAOgEQAHgDAIAAIAPgDIASgBIARgBIAOABIAOACIAOAEIAOADIANAIIALAIIALAIIALAIIAJAKIAIAJIAHALIAIAMIAFANIAFANIADAOIACACIAHAOIAGAPIAEAIIAGAIIAHALIAHAMIAGANQAMAfACAhQACAaAAAbIAAA0IAAA0QAAAagFAbIACARIACASIAAARIABANIAAAMIAAAMIAJAIIAJAKIAIAMIAHALIAFANIAFAOIAJAKIAGALIAGANIAFALIACAOIABAOIgBAMIgCANIgDALIgFAMIgGAKIgIALIgHAJIgJAHIgKAHIgKAHIgMAFIgLADIgNACIgMABIgSAAIgRAAIgSAAIgKAIIgLAHIgMAEIgNAGIgLAFQgPABgOACIgiADIgWAAIgXAAg");
	this.shape_9.setTransform(0.025,-119.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#999999").s().p("AA4G6IgSAAIgggFIgKgDIgNgFIgMgFIgMAGIgOAEQgHADgGAAIgQACIgQACIgOgCIgOgEIgOgEIgOgGIgMgGIgGgEIgKgCIgLgEIgKgFIgMgGIgMgEIgOgFIgKgGIgMgKIgNgJIgNgKIgLgKIgJgKIgKgLIgJgMIgIgMIgIgMIgFgJIgFgIIgIgOIgJgOIgGgJIgEgMIgFgYIgDgZIAAgcIABggIADggIADgPIAEgQIAFgMIAEgLIAHgMIAIgKIAIgJIAJgLIALgLIALgLIgEgNIgEgMIgDgNIAAgNIAAgNIABgNIADgMIAEgNIAHgLIAGgKIAIgLIAHgLIAJgKIAMgKIAOgKQAAgHADgIIAFgPIAGgPIAJgNIAIgMIAIgLIAJgLIALgJIANgJIAHgJIAGgJIAfgYIAXgQIAcgPQANgIAPgGQAOgFAOgDQAVgEAVgBIAPgGIAOgEIAPgDIAQgDIASgBIASgBIAPACIAOACIAPACIAOAFIANAHIALAJIALAIIAMAJIAJAKIAJAJIAHALQAEAGAEAHIAGANIAFAOIADAOIABABIAIAQIAGAPIAEAIIAGAHIAHANIAIAMQACAIAEAFQAMAhACAiQACAaABAbIAAA2IAAA2QAAAbgGAcIADASIABASIABASIABAMIAAANIAAAMIAJAJIAJAKIAJALIAGANIAFANIAGAOIAJAKIAHAMIAFANIAFAMIADAPIAAANIAAAOIgCAMIgEAMIgEAMIgHALIgIAKIgIAJIgJAIIgKAIIgLAHIgLAEIgNAEIgMACIgMABIgTAAIgSAAIgSAAIgKAIIgMAHIgMAFIgNAGIgNAEIgdAEIgiADIgYAAIgXAAg");
	this.shape_10.setTransform(0,-132.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#999999").s().p("AA6HHIgTgBIghgEIgLgDIgNgFIgMgFIgMAFIgOAFIgOADIgQACIgQABIgPgBIgOgEIgPgFIgOgGIgOgGIgFgEIgLgDIgLgDIgKgFIgMgGIgNgFIgNgFIgLgGIgNgKIgNgJIgNgKIgMgLIgJgLIgKgLIgJgMQgGgGgDgGIgIgNIgFgJIgFgIIgIgOIgKgPIgGgJIgEgMIgFgaQgDgNAAgNIAAgcIABghIADghIACgPIAFgQIAFgNIAFgMIAHgLIAIgLIAIgJIAJgLIALgMIAMgLIgEgNIgEgNIgDgNIgBgOIAAgNIABgNIADgOIAFgMIAHgLIAGgMIAIgKIAIgLIAJgKIAMgLIAOgKIADgQIAGgQIAHgOIAJgOIAIgMIAIgLIAKgMIAKgKIANgJIAHgJIAIgKIAegXIAZgRQAOgJAOgHQAOgIAPgGQAPgFAOgDQAWgFAVAAIAPgGIAPgFIAQgDIAQgCIATgCIASgBIAPACIAPACIAPADIAOAEIAOAIIAMAIIALAJIAMAJIAJAKIAJAKIAIAMIAIANIAGANIAEAOIAEAOIACACIAHAQIAGAQIAGAIIAFAIIAHAMIAIANQADAHAEAHQAMAhACAjQACAbABAcIAAA3IAAA4QAAAcgGAcIADATIABATIABASIABANIAAANIAAANIAKAJIAJAKIAIAMIAHANIAFANIAGAOIAJALIAIAMIAFANIAFANIADAOIAAAPIAAANIgCANIgEANIgFAMIgHALIgIALIgHAJIgJAIIgMAIIgKAHIgMAFIgNADIgNADIgMAAIgUAAIgSAAIgTAAIgKAJIgMAHIgNAFIgNAGIgMAFIggAEIgjADIgXAAIgYAAg");
	this.shape_11.setTransform(0,-146.175);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#999999").s().p("AA7HVIgTgCIghgFIgMgCIgNgGIgNgFIgMAGIgPAFIgOACIgQACIgRACIgQgCIgOgDIgPgGIgOgFIgOgHIgGgDIgKgEIgNgDIgLgGIgLgFIgOgFIgNgFIgLgGIgOgLIgNgJIgNgLIgNgLIgIgMIgLgKIgJgNQgGgFgDgIIgIgNIgGgJIgFgIIgJgPIgJgPIgGgKIgFgLIgFgbQgDgOAAgNIgBgdIACgiIADgiIACgQIAGgQIAEgOIAGgLIAHgLIAIgMIAIgKIAJgKIAMgNIAMgMIgEgNIgFgOIgCgMIgBgPIAAgMIABgPIADgNIAFgNIAHgMIAHgLIAIgMIAIgLIAJgKIANgKIANgLIAFgQIAEgRIAIgPIAJgOIAIgMIAJgMIAKgMIAKgKIAOgJIAHgKIAIgKIAggYIAZgRIAdgRQAOgJAPgEQAPgHAPgCQAXgFAVgBIAQgGIAQgEIAQgEIARgDIATgBIASgBIAPACIAQACIAQADIAPAEIANAIIAMAJIAMAJIAMAJIAJAKIAJALIAJAMIAIANQADAHADAHIAFAPIAEAOIABACIAIAQIAGARIAGAIIAGAIIAGANIAJANIAHAOQAMAiADAlQACAbAAAcIAAA5IAAA6QAAAdgGAdIADASIABAUIABATIABANIAAAOIAAANIAKAJIAJAKIAJANIAHANIAGAOIAGAOIAJALIAHANIAHANIAEAOIAEAOIAAAPIAAAOIgDANIgDANIgGANIgGALIgIALIgIAKIgKAIIgMAIIgLAHIgMAGIgNADIgNACIgOABIgTAAIgTAAIgTAAIgKAJIgNAHIgNAGIgOAFIgNAGIgfADIgkAEIgZABIgZAAg");
	this.shape_12.setTransform(0,-159.45);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#999999").s().p("AA9HiQgKgBgKgCIgigEIgMgDIgOgFQgHgCgFgEIgOAGIgOAFQgIACgHABIgRACIgRACIgQgCIgPgDIgQgGIgNgGIgPgGIgHgFIgKgCIgMgFIgLgFIgNgGIgNgEIgOgGIgLgGIgOgLIgOgKIgOgLIgMgLIgJgMIgLgLIgKgMQgFgHgEgHIgIgNIgGgKIgGgJIgJgPIgKgPIgFgKIgFgMIgFgbIgEgbIgBgfIACgiIAEgjIACgRIAGgRIAEgOIAGgMIAIgLIAHgMIAJgKIAJgLIANgNIAMgMIgEgNIgFgPIgDgMIAAgPIAAgNIABgQIADgNIAFgOIAGgLIAIgMIAIgMIAIgLIAJgLIAOgLIAOgLIAEgRQACgIADgIIAIgPIAJgPIAIgMIAJgNIAKgMIAMgKIANgKIAIgKIAIgKIAggYIAagSIAegSQAPgIAQgGQAPgGAPgDQAXgEAWgBIAQgHIAQgEQAJgCAIgBIASgDIATgCIATgBIAQACIAQACIAPADIAQAFIAPAIIAMAJIALAJIANAKIAKAKIAJALIAIAMQAFAHAEAHQADAHACAHIAGAPIAEAOIACADIAHAQIAHARIAFAJIAGAIIAIANIAIAOIAHAOQANAjADAlQACAdAAAeIAAA5IAAA8QgBAdgFAfIADATIABATIABAUIABAOIAAANIAAAPIAKAJIAKAKIAJAMIAHAPIAHAOIAFAOIAJAMIAIANIAHANIAEAPIAEAPIABAPIgBAOIgDANIgEAOIgFANIgGALIgJAMIgIAKIgKAIIgLAJIgNAHIgMAFIgNAEIgOACIgOABIgTAAIgUAAIgUAAIgKAJIgOAIIgNAFIgOAGIgNAGIghADIglADIgZACIgZAAg");
	this.shape_13.setTransform(0,-172.75);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#999999").s().p("AA+HuQgKAAgKgCIgjgEIgMgDIgPgGIgMgGIgOAHIgOAFIgQADIgSACIgRACIgQgCIgPgEIgQgFIgPgHIgPgHIgGgEIgLgDIgNgEIgLgFIgNgHIgOgEIgOgGIgMgGIgNgLQgIgFgHgGIgOgLIgNgLIgJgMIgLgMQgGgFgEgIQgGgGgEgHIgIgOIgGgKIgGgJIgJgPIgKgQIgHgKIgEgNIgGgcQgCgOgBgOIAAgfIABgjIAEgkIADgRIAEgRIAGgOIAFgNIAIgMQADgGAFgGIAJgKIAJgMIANgNIANgMIgEgOIgFgOIgDgOIgBgPIAAgOIACgPIACgOIAFgOIAHgLIAIgNIAIgMIAJgMIAJgLIAOgLIAOgLIAFgRIAFgRIAIgQIAJgPIAJgNIAJgNIALgMIALgKIAOgKIAIgLIAIgKIAigZIAagTQAOgJAQgJQAPgIARgGQAQgGAPgDQAXgFAXgBIARgGIAQgFIARgDIATgDIATgCIATgBIARACQAIACAIAAIARAEIAQAEIAOAIIANAKIAMAJIAMAKIALAKIAJAMIAJAMIAIAOQAFAIABAHIAGAQIAEAOIABADIAIAQIAHASIAGAIIAGAJIAIAOIAIAOIAIAPQANAjADAnQACAdAAAeIAAA8IAAA9QgBAegFAfIADAUIABAUIABAUIABAOIAAAOIAAAPIAKAJIALALIAJANIAHAOIAHAPIAFAPIAKAMIAIAMIAHAPIAFAOIACAPIABAQIgBAOIgBAPIgFANIgFAOIgHALIgIAMIgJAKIgKAJIgMAJIgMAHIgNAFIgOAEIgNADIgPABIgTAAIgVAAIgVAAIgLAJIgMAIIgPAFIgOAHIgNAFIgiAEIgmADIgaABIgaAAg");
	this.shape_14.setTransform(0,-186.025);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#999999").s().p("ABAH7QgKAAgLgCIgkgEIgNgEIgOgFIgOgGIgNAGIgPAFIgQAEIgSACIgSACIgRgCIgQgEIgQgGIgPgGQgIgDgHgEIgHgEIgLgEIgNgEIgLgFIgNgHIgPgFIgOgFIgMgHIgPgLIgOgLIgPgLIgNgMIgKgMIgLgMIgKgNQgGgHgEgHIgJgPIgFgKIgGgJIgKgPQgEgJgGgIIgHgKIgEgNIgGgdIgDgdIgBgfIACglIAEglIACgRIAGgSIAEgOIAGgNIAIgMQAEgHAFgGIAJgKIAJgMIANgOIAOgMIgFgOIgFgPIgDgOIgBgPIAAgPIACgPIADgPIAFgOIAHgMIAIgNIAJgMIAJgMIAJgLIAOgMIAPgLIAEgSIAGgRIAIgRIAJgPIAJgNIAKgNIAKgNIAMgLIAPgKIAIgKIAIgLIAigaIAbgTIAggSQAPgJARgGQAQgGAQgDQAYgFAYgBIAQgHIARgEIASgEIASgDIAUgCIAUgBIARACIARADIARADIAQAFIAPAIIANAKIANAJIAMAKIALALIAJAMIAJANQAFAGAEAIIAHAPIAFAQIAEAPIACADIAIARIAHASIAGAJIAGAIIAIAOIAJAPIAHAPQAOAlACAnQADAeAAAfIAAA9IAAA/QAAAfgGAgIACAUIACAVIABAUIABAPIAAAOIAAAPIALAKIAKALIAKANIAHAPIAHAPIAGAPIAJAMIAJANIAHAPIAEAPIAEAQIABAQIgBAOIgDAPIgEAOIgFAOIgHAMIgJAMIgJAKIgLAJIgLAJIgNAIIgNAFIgOAEIgOADIgPABIgUAAIgVAAIgVAAIgLAJIgOAIIgPAGIgOAGIgOAGIgiAEIgnADIgbABIgaAAg");
	this.shape_15.setTransform(0.025,-199.325);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#999999").s().p("ABCIIQgLAAgLgCIglgFIgMgDIgQgGQgHgCgGgEIgPAHIgPAFQgIADgIAAIgTADIgSACIgQgCIgRgEIgQgGIgQgHIgQgHIgGgEIgMgDIgNgFIgMgFIgOgHIgOgFIgPgGIgNgHIgOgLIgPgLIgOgMIgPgMIgJgMIgMgNIgLgNQgFgHgFgHIgJgPIgFgKIgGgKIgKgQIgKgRIgIgKIgEgOIgGgdQgDgPAAgPIgBggIACglIAEgnQABgJABgIIAGgSIAFgPIAFgNIAJgNQAEgHAFgFIAJgLIAJgNIAOgNIAOgNIgFgPIgFgPIgDgOIgBgQIAAgPIACgPIADgPIAFgPIAHgMIAIgNIAJgNIAJgMIAKgMIAOgLIAQgMIAEgSIAGgSIAIgRIAKgQIAJgNIAJgOIALgNIANgLIAOgKIAIgLIAJgLIAjgbIAcgTQAPgKASgJQAPgJARgGQAQgGARgEQAYgFAZAAIARgHIARgFQAKgDAIAAIATgEIAVgBIAUgCQAJACAJAAQAIACAJABIARADIARAFIAPAJIAOAKIAMAKIAOAKIALALIAJAMIAJANIAKAPIAGAPIAFARIAFAPIABADIAJARIAHASIAGAKIAGAJIAJAOIAIAPIAIAPQAOAmADAoQACAfAAAgIAAA/IAABAQAAAggGAgIADAVIACAWIAAAVIABAPIAAAOIAAAPIALAKIALAMIAKANIAHAPIAHAQIAHAQIAKAMIAIANIAHAPIAFAPIADARIABAQIgBAPIgDAPIgDAPIgGAOIgIAMIgJAMIgJALIgLAJIgLAKIgNAHIgOAGIgOAEIgOADIgQAAIgUAAIgWAAIgVAAIgMAKIgOAIIgPAGIgOAHIgPAGIgjAEIgoADIgbABIgbAAg");
	this.shape_16.setTransform(0,-212.625);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#999999").s().p("ABEIVQgMAAgKgCIgngFIgNgDIgPgGIgOgHIgOAHIgRAGIgQADIgTACIgTACIgRgCIgRgDIgRgHIgPgHIgQgHIgIgEIgLgDIgOgFQgGgDgGgDIgOgGIgPgGIgPgFIgMgHIgQgNIgPgLIgPgLIgPgNIgJgNIgMgMQgGgHgFgIQgGgGgFgIIgJgPIgFgKIgGgKIgKgQIgLgRIgHgMIgFgOIgGgeIgEgeIAAghIABgmIAFgoIACgSIAGgSIAFgPIAGgOIAJgNIAJgNIAJgKIAKgNIAOgOIANgNIgEgPIgFgQIgDgPIgBgQIAAgOIACgRIACgQIAGgOIAHgNIAIgNIAJgNIAKgMIAKgMIAOgNIAQgLIAEgTIAGgSIAJgSIAKgQIAJgNIAKgPIAMgNIAMgLIAQgLIAIgLIAIgLIAkgbIAdgUQAPgKARgKQARgIARgGQARgIARgDQAagFAZgBIARgHIARgFIATgEIAUgCIAUgDIAVgBIASADIASACIARADIARAGIARAIIAMALIAPAJIAMALIAMALIAKANQAFAGAEAHIAKAPQAEAIACAIIAGARIAEAPIACAEIAJARIAHATIAFAKIAIAJIAIAOIAJAPIAIARQAOAmADAqQACAfAAAhIAABAIAABCQAAAggGAiIADAVIACAXIABAUIAAAQIAAAPIAAAPIALAKIAMANIAKANIAHAQIAHAQIAHAPIAKAOIAJANIAHAPIAFAQIAEARIAAARIAAAPIgDAQIgFAOIgFAOIgIANIgJANIgJALIgMAJIgMAJIgNAIIgNAHIgQADIgOADIgPABIgWAAIgWAAIgWAAIgMALIgOAIIgQAFIgPAHIgOAHIgkADIgpAEIgcABIgbAAg");
	this.shape_17.setTransform(0,-225.9);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#999999").s().p("ABFIiQgLAAgLgCIgngFIgOgEIgQgFIgOgHIgOAHIgRAFIgRAEIgTADIgTABIgSgBIgRgFIgSgGIgQgHIgRgIIgGgEIgNgEIgNgDIgNgHIgOgHIgQgFIgPgGIgNgHIgPgMIgQgMIgPgMIgPgNIgKgNIgMgNQgGgGgGgIQgFgHgFgIIgKgQIgGgKIgFgKIgKgRIgMgRIgHgMIgFgOIgGgfIgEgfIAAgiIABgnIAFgoIADgSIAFgTIAFgQIAHgOIAIgNQAEgHAGgGIAJgLIAKgOIAOgOIAOgNIgEgQIgGgPIgDgQIgBgQIAAgPIACgRIADgQIAGgPIAHgNIAJgOIAJgNIAKgNIAKgMIAPgMIAQgNIAFgTIAFgTIAJgRIAKgRIAKgOIAKgOIAMgOIAMgLIAQgLIAIgMIAJgLIAlgcIAdgUQARgLARgJQARgJASgHQARgGARgEQAagGAaAAIASgHIASgGIATgDIAUgEIAVgBIAWgCQAIACAKAAIASAEIASADIARAFIAQAJIAOALIAOAKIANAKIAMAMIAKANIAKANIAKAQIAGAQIAGASIAEAQIADADIAIASIAHATIAGAJIAIAKIAIAPIAKAQIAIAQQAOAoADAqQACAgAAAiIAABBIAABEQAAAigGAhIADAXIACAWIABAWIAAAPIAAAQIAAAQIAMAKIAMAMIAKAPIAIAQIAGAPIAHARIAKAOIAJANQAFAIADAIIAFAQIADARIABASIgBAPIgCAQIgFAPIgFAOIgIAOIgJAMIgKAMIgLAKIgNAJIgNAIIgOAGIgQAFIgPACIgPABIgXAAIgWAAIgXAAIgMAKIgOAJIgQAGIgPAHIgPAGIglAFIgqADIgdABIgcAAg");
	this.shape_18.setTransform(0,-239.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#999999").s().p("ABGIvQgLAAgLgCIgogGIgOgDIgQgGIgPgHIgPAIIgQAFQgKADgIAAIgUAEIgTABIgTgBIgRgFIgSgHIgQgGIgRgIIgIgFIgMgDIgOgFIgNgGIgPgHIgPgGIgQgGIgNgHIgQgNIgQgLIgPgMIgQgOIgKgNIgNgOIgLgOQgHgHgEgIIgKgRIgGgKIgGgKIgKgRIgMgSIgHgMIgFgPIgHgfIgDggIgBgjIACgnIAEgqIADgTIAGgSIAGgRIAGgOIAJgOIAJgNIAKgMIALgNIANgPIAPgOIgFgPIgFgQIgDgQIgCgRIAAgPIADgRIADgQIAFgQIAIgNIAJgPIAKgMQAEgIAGgGIAKgMIAPgNIAQgNIAFgTQADgKAEgKIAIgRIALgRIAKgPIAKgOIALgPIAOgLIAPgMIAJgMIAJgLIAmgcIAegVQAQgLATgKQAQgKATgGQASgHARgEQAagEAbgCIATgGIASgGQAJgDAKAAIAUgFIAXgBIAWgCIASADIASACIATAEIASAFIAQAJIAPALIANALIAPAKIALANIAKANIAKANQAGAIAEAJIAHAQIAHASIAEARIABACIAJATIAIATIAGAKIAIALIAJAOIAJAQIAIASQAPAnADAsQADAhgBAjIAABDIAABFQAAAigGAjIADAWIACAYIABAWIAAAQIAAAQIAAAQIAMALIAMAMIALAPIAIAQIAHAQIAGARIALAOIAJAOIAIAQIAGARIADARIABASIgBAQIgDAQIgFAPIgFAQIgIAMIgKAOIgJAMIgMAJIgNAKIgNAIIgPAHIgQAEIgQADIgPABIgXAAIgXAAIgXAAIgMALIgQAIIgQAHIgPAGIgPAHQgUABgSAEIgrADIgdABIgeAAg");
	this.shape_19.setTransform(0,-252.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#999999").s().p("ABII8QgLAAgMgCIgpgGIgOgDIgQgHQgJgCgHgEIgPAHIgRAGIgSADIgUADIgUACIgTgCIgSgEIgSgHIgRgHIgRgIIgIgFIgMgDIgPgFIgNgGIgPgIIgPgFQgJgDgIgEIgOgHIgQgNIgQgMIgQgMIgQgOIgKgOIgNgNIgMgPQgGgHgFgJIgJgQIgHgLIgGgLIgLgRIgMgSIgHgMIgFgPIgGghIgEggIgBgjIACgpIAEgqIADgUIAGgTIAGgRIAGgPIAJgNQAFgIAFgGIAKgMIALgOIAOgPIAPgOIgFgQIgFgRIgEgPIgBgSIAAgQIACgRIAEgRIAFgPIAIgOIAKgPIAJgNIAKgOIALgMIAPgNIARgNIAFgUIAGgUIAJgSIALgSIAKgOIAKgPIANgPIANgMIARgLIAIgMIAKgMIAmgdIAfgVQARgLASgKQARgKATgHQASgHASgEQAbgFAbgBIATgHIATgGQAKgDAKgBIAUgDIAXgCIAWgCIATADIATADIATADIATAGIARAJIANALIAQALIANALIANAMIAKANIAKAPQAFAHAFAJQAEAJADAIIAHASQACAIACAJIACADIAJATIAIAUIAHAKIAHALIAJAPIAKAQQADAJAFAJQAPApADAsQACAiABAjIAABFIAABHQgBAjgGAkIADAWIACAYIABAXIABARIAAAQIAAAQIAMALIAMANIALAPIAIAQIAHARIAHASIALANIAJAPIAIARIAFAQIAEASIABASIgBARIgDAQIgEAQIgHAQIgIANIgJAOIgKAMIgMAKIgOAKIgNAIIgPAGIgQAFIgQADIgQABIgXAAIgYAAIgYAAIgNALIgOAIQgJAEgIADIgQAHIgQAHQgTABgTADIgtAEIgdABIgeAAg");
	this.shape_20.setTransform(0,-265.775);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#999999").s().p("ABJJJQgLAAgMgCIgqgGIgPgEIgQgGQgJgDgHgEIgQAIIgRAFQgJADgJABIgVADIgUACIgTgCIgTgFQgJgCgJgEIgSgIQgJgDgIgFIgIgEIgNgEIgOgFIgOgGIgPgIIgQgGIgRgGIgOgIIgQgNIgRgMIgRgNIgQgOIgKgOIgOgOQgGgGgFgJQgHgHgFgJIgJgRIgHgLIgHgLIgKgRIgNgTIgHgMIgFgPIgHgiQgDgRgBgQIAAgkIABgqIAFgrIADgUIAGgUIAGgRIAGgPIAKgOQAEgHAFgHIALgMIALgOIAPgQIAPgOIgGgQIgFgRIgDgQIgBgSIAAgRIABgRIAEgRIAFgQIAJgOIAJgPIAKgOIAKgOIALgNIAQgNIASgNQABgLADgKIAHgUIAJgTIALgSIAKgPIALgPIAMgPIAOgMIARgMIAJgMIAJgMIAogeIAfgWQARgLATgKQARgKAUgHQASgHATgEQAbgFAcgBIATgIIAUgFQAKgDAKgBIAVgEIAXgCIAXgCIAUADIATADIATAEIATAFIARAKIAPALIAPALIAOALIANANIAKANIALAPQAFAIAFAJIAHARIAHATIAEARIACADIAKAUIAIAUIAGALIAIAKIAJAQIAKAQIAIASQAQAqADAuQACAiAAAkIAABHIAABIQAAAkgGAkIADAYIACAYIAAAXIABARIAAARIAAARIANALIAMANIALAPIAJARIAHARIAHASIALAOIAKAPIAIARIAFARIAEASIABATIgBARIgDARIgEAQIgHAQIgIANIgKAOIgKAMIgMALIgOAKIgOAJIgQAGIgPAFIgRADIgQABIgYAAIgYAAIgZAAIgMALIgQAJIgRAGIgQAIIgQAGIgnAFIguAEIgeABIgfAAg");
	this.shape_21.setTransform(0.025,-279.075);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#999999").s().p("ABMJWQgMAAgNgCIgrgGIgOgEIgRgHQgJgCgIgEIgQAHIgSAGQgJADgJABIgVADIgVACIgUgCIgSgFIgUgHIgRgHIgSgIIgIgFIgNgEIgPgFQgIgDgFgEIgQgHIgRgGIgRgHIgOgHIgRgOIgRgMIgRgOIgQgOIgLgOIgOgOQgGgHgGgJQgGgHgFgJIgKgRIgHgMIgHgLIgLgSIgMgTIgHgNIgGgPIgHgiQgDgRgBgQIAAgmIABgrIAFgsIADgUIAHgUIAFgSIAHgPIAJgOQAEgIAGgHIALgMIALgOQAIgJAHgHIAQgPIgGgRIgFgRIgEgQIgBgTIAAgQIADgTIADgRIAGgQIAIgPIAKgPIAKgOIAKgOIALgOIARgNIASgNQABgLADgLIAHgUIAJgTIALgTIALgPIALgPIAMgQIAPgMIARgMIAJgMIAKgNIAngfIAhgWQARgLAUgKQARgLAUgGQATgIATgEQAdgGAcgBIATgHIAUgGIAUgEIAWgEIAYgCIAXgCIAUADIAUADIAUAEIATAGIASAJIAOAMIAPALIAQAMIAMANIALANQAGAIAEAIQAHAHAEAKQAEAIADAJIAHATIAFASIACADIAJAUIAJAVIAGALIAIAKIAJAQIALARIAIASQAQAsADAuQADAjAAAlIAABIIAABKQAAAlgHAlIADAYIACAZIABAYIABARIAAARIAAARIAMALIANAOIALAPIAJARIAIASIAHASIALAPIAKAPIAIARIAGASIADASIABAUIgBARIgCARIgFAQIgHARIgIAOIgLAOIgKAMIgMALIgOAKIgOAJIgQAHIgRAFIgRACIgQABIgYAAIgZAAIgZAAIgNAMIgQAJIgRAHIgRAHIgQAHIgoAFIguAEIggABIgeAAg");
	this.shape_22.setTransform(0,-292.375);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#999999").s().p("ABNJiQgMAAgNgCIgrgGIgQgDIgRgHQgJgDgHgEIgRAIIgSAGQgKACgJABIgVAEIgWACIgUgCIgTgGIgTgGIgSgIIgSgIIgIgFIgOgEIgPgFIgPgHIgPgIIgSgFIgRgIIgOgIIgRgNIgSgNIgRgNIgRgPIgLgPIgOgOIgMgQQgHgHgFgKIgKgRIgHgMIgHgLIgLgSIgNgUIgHgNIgGgQIgHgjQgDgRgBgQIAAgnIABgrIAFgtIADgVIAGgVIAGgSIAHgQIAKgOQAFgIAFgHIALgNIAMgOIAPgRIAQgOIgGgSIgFgRIgEgRIgBgSIAAgRIACgTIAEgSIAFgQIAJgPIAKgQIAKgOQAFgIAGgHIALgNIARgOIASgOIAFgWIAGgUIAKgUIAMgSIALgQIALgQIANgQIANgNIASgLIAJgOIAKgMIAqggIAggWQATgMATgKQASgKAVgIQATgIATgEQAdgFAdgBIAUgIIAUgGQAKgDALgBIAWgEIAZgBIAXgCIAVADIAUACIAUAEIATAGIASAKIAQAMIAQALIAOAMIANAOIALANIALAPIALASQAEAJADAJIAHATIAFASIACADIAKAVIAIAVIAHALIAIALIAJARIALARQAEAKAFAIQAQAsADAwQADAlAAAlIAABKIAABLQAAAlgHAnIADAYIACAZIABAYIABASIAAASIAAARIANAMIANAOIALAPIAJASIAHASIAIASIAMAPIAJAQIAJASIAGARIAEAUIAAATIAAARIgDASIgFARIgGARIgJANIgLAQIgLAMIgMALIgPALIgOAJIgQAGIgRAFIgRADIgRABIgZAAIgZAAIgZAAIgOAMIgQAJIgRAHIgRAIIgRAGIgqAGIgvADIgfABIggAAg");
	this.shape_23.setTransform(0,-305.65);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#999999").s().p("ABOJwQgMAAgNgCIgsgHIgQgDIgRgHQgJgDgIgFIgRAJIgSAGQgLADgJAAIgWADIgVADIgVgDIgUgEIgUgIIgSgIIgTgIIgIgFIgNgEIgQgFQgIgDgHgEIgPgIIgSgGIgSgHIgPgIIgRgOIgSgNIgSgOIgRgPIgLgOIgOgQQgHgGgGgKQgHgHgEgKIgLgSIgHgMIgHgLIgLgTIgOgUIgIgNIgFgQIgHgkQgDgRgBgSIgBgnIACgsIAFguIADgVIAGgWIAHgSIAHgPIAKgPQAEgJAGgHIALgMIALgQIAQgQIARgPIgGgSIgFgSIgFgRIgBgTIAAgRIACgUIAFgSIAFgQIAJgPIAKgRIALgOIAKgPIAMgOIARgOIASgOIAGgWIAHgWIAJgUIAMgTIALgQIALgQIAOgPIAOgOIASgMIAKgNIAKgNIApggIAigXQATgMATgLQATgKAVgIQATgHAUgFQAegFAdgCIAUgIIAVgFQALgEALgBIAWgDIAZgCIAZgDIAUAEIAUACIAVAEIAUAGIATAKIAPANIAQAMIAQALIAMAOIAMAOIALAQQAGAIAFAKIAHASIAIAUIAEASIADAEIAKAUIAIAWIAHAMIAIALIAJARIAMARIAJATQAQAtADAwQADAmAAAmIAABLIAABNQAAAmgHAnIADAZIACAaIABAZIABASIAAASIAAASIAOAMIANANIALAQIAJASIAIATIAHATIAMAPIAKAQIAJASIAGASIAEATIABAUIgBASIgDASIgFARIgGARIgJAPIgLAPIgLANIgNALIgPALIgOAJIgRAHIgRAFIgSADIgRABIgaAAIgZAAIgaAAIgOAMIgQAJIgSAHIgSAIIgRAIIgpAEIgxAFIggABIghAAg");
	this.shape_24.setTransform(0,-318.95);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55,-381.3,110,412.7);


(lib.hobbithouse_2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AxZjZQAAAAAAAAQAVhVAQg+QAiiKAHgeIBGAAQAPALAQAKQApAZAvAOQAPAEBbATQA2ALAWATQAdAaAAA4QAAAbgEAlQAHACAIACIAAAFAupn5QAAAtgLAuQgLAsABAXQCeAhAwAMQABAAACABQABAAAAAAQAmAJBHATQgEAxgLBAQgFAjgKA4QARAFARAFAwellIAyAAQAYAFAWAFAwAlfQgLAAgTgGQgDgBgDAAQgFgCgFgCAyLg7QAEADAFADQAWhbAThJQBXAkBlAiQAzARA2AQQADABACAAQBFAVBNAXQgJAygNBDQgBAIgBAHQgNBJgHA8QgGAwgCAoQgEA4AEAnQACAVAEARAyCg1QAmAZBGAMQAUAEAWADQAZgiAUgtQARgnAPgOAvsgJQAYADAbAEQAXAFAVADQAoAGATADQAMABADABQAzAIAgALQAeAKAdARQAEADAEACAs0hyQACgEAjhrQAQgxASgbArfDPQALgGALgFQD0h0DIgiQCogdFoAAQGUAAEZC4QCiBqCjDVQADADACAEArREcQAOADAQACArRF7QDJgCEzABQGKABBkgHQAfgCACgDIAAAAQAAgOgIAEQgQAJgKABQAQAAASAAQDdAHGvBTAtSAPQAAARgNAsQgPAygCAOQgDASgFApQgEAggDARQAkAIAiAIQAtAKA7AKAy9CyQBVASBLARQBVASBJARQgBACAAADAwtGGQgBADAAAEIgFAAAwfDeQgDAtgCAzQgCAdgFAhQgBAFgBAFQAWgCAWgBQBegGDSgCAzICrIAAAFQAFABAGABQAgh/AbhoAz5GhQACgHACgGQBtgJBbgFA0xGZQAegDAegCQAeh5AahpAPGHOIATAAQAsAOA8ANQAhAHA9ALAT1IIQAeAGAfAHASgH2QApAIAsAK");
	this.shape.setTransform(0,0.025);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#666666").s().p("AiNHEQAGghACgdIAFhgIACgJICcAjIgBAEIABgEIBHAPQAtALA7AKQgEA3AEAoQjRAChfAGIgrACIABgJgAh+EdIiggjIA7jpQAmAaBGAMIApAHIgpgHQhGgMgmgaIAoiiQBYAkBkAiIgBAFQgPAPgSAnQgTArgaAjIA0AHQAXAFAUAEIA7AJQAAARgOArQgPAzgCAOIgIA7QgDAggEARIicgjgABugpIgEgBIAlhvQAPgyATgbIABABQAmAIBHAUQgEAwgLBBIgPBZIiTgqgAhNkdIgyAAIgGgCIgLgDIgGgDIAqinIBGAAQAPALAQAKIgDAGQAAAtgLAuQgLAsAAAWIgtgJg");
	this.shape_1.setTransform(-92.65,-7.15);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFCC").s().p("AkDDoICfAjIgCAJIgEBgQgDAdgFAhIgBAJQhcAGhtAJIA5jigACAE9IhHgPQAEgRADggIAIg7QACgOAPgzQANgrAAgRIAQACQAyAHAhALQAeAKAcASQgNBJgHA8IgWAKIAWgKQgGAwgCAoQg7gKgsgLgADJBZQghgLgygHIgQgCIg7gJQgVgEgWgFIgzgHQAagjATgrQAQgnAPgPIACgFQAzARA2AQQg2gQgzgRQhkgihXgkIAAAAIAliUIAGADIALADIAFACIAzAAIAtAJQgBgWAKgsQAMgugBgtIAEgGQAoAYAvAPQAPAEBbATQA3ALAVATQAdAaAAA3QAAAcgEAlQhHgUgmgIIgBgBIgDgBQgwgLidgiQCdAiAwALIADABQgSAbgQAyIglBvIAFABICSArIgVB2IgDAPQgcgSgegKgAhHkpQgLgBgTgFQATAFALABg");
	this.shape_2.setTransform(-95.3,-5.35);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#336633").s().p("AOPDqIgBAFIhegTQg8gMgsgOIgTAAIAAgFQmvhTjdgHIAAAAQAAgOgIAEQgQAJgKABIABAFQhiAHmMgBQkzgBjIACQgEgoADg3IAeAFIgegFQACgnAGgwQD0h0DJgjQCngcFpAAQGTAAEZC3QCiBpCjDWIhVgSg");
	this.shape_3.setTransform(27.2683,26.85);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.hobbithouse_2, new cjs.Rectangle(-134,-54.3,268,108.69999999999999), null);


(lib.hobbit_house1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("Aa5vUQABgDABgEQAEgSAFgRQABgGACgGA9+ruQAFgOAFgOIAAAAQBdkHBJiEQB+jgDHiQQHvlnSVAAQGzAAKeI8QC1CZCtCvQAHAGAGAHQAiAjAiAjQAAABABAAQABABAAABQABAAAAABQABAAAAABQABAAAAABQABAAAAABQAAAAABABQAAAAABAAQAFAHAGAGAb2uSQACACADABQABABABAAQAAABABAAQABAAAAABQABAAABAAQAAABABAAQAAAAABABQAAAAABAAQAHAFAHAFQADACADACQBMAzA1BNQAAABAAAAQAAAAAAAAQAWAgASAkQACAEADAFQAJAVALAaIAHgBIAMAAAdbsyQAfAiAXAaAfGquQAPARALAbQAAAAAAAAQAAABABABQARApAPA8QATBLAQBpQABACAAABQAGgEAJgBQAAAAABAAQAGABAHgCQARgCABAAEAg1gFpQACgBADAAQAEAAAEAAEAglgFkQAAABAAABQADAWAEAYQAaC7ADBbQASgCAegCEAgBgIbQAQAsARAzAfap/QASArAVA5A93sLQgjBPghBTQhACjgNCMQgFAygXFdQgVEygQCFQgWC0gIBLQgNCMgCB9QgBANgCBjQgCBEAAAjIAACCQAAAHACDIQADDVAABGIAZAAQCBASDZADQBDABAsAAQABAAAAAAQBcgBAAgGQAAgHgqADQgVABgeADIBdAAIDIAAQACgHAEgNQAEgSAHgbQANg6AAgWQAAgngVgoQgRgfgWgUA2AaFIgKAAQgEgZgEgYQgVh5gZhrQgdh6gMg0QgjijAAkeQAAjLAIhVQAJhnAdhFQAag+BChYQBjh9BJheQDBj6B/hGQBIgoBcgQQBSgOCGAAQDhAAC+AOQAiADAgADQE9AdDXBIQG4CSBqFWQB9GPB7FLQAkBrANBUQANBaAACQQAABggNB2QgJBWgOBOQgDgPAAgIIgFAAAi5l8QAigCAZgKQAHgDAKgEQAUgIAfgNAjQl8QAMAAALAAAiomGQgIAFgJAFQhIAsgmBcQgkBVgTCjQgMBjgTD3QgXD2giDBQhDGAAGDAQABArALBrQAIBSABBIQAAAKAAAKAj4M9IAMAAIBsAAQAwAaAzAEIBGAAIAKAAAj7NHQAAAFgDAEQgCAFAAAGIAAAPQAAgGAGgLQABgCACgCQABgBAAgBQAFgHAFgFIAAAZAw2LPIAUAAQgBAcgJAxQgKA7AAAJQAABAAyALQARAEAdgBQAPgBAdgCQAwAAA2ACQAfgBAJgMQAHgKAEgqQAHhDAKgyAwiLFQAAAFAAAFIDSAAQATAEAsAGQAMACAKACQAAAAAAAAQABAAABAAQAOADAJADAo7c+QAAALh8AAQhTAAkvgBQhJAAhoADQhuAEgRADAj3NVQAIA0AxAqQAxAqA1AAQA+AAAYgqQAUg2AXgYAo7c+QAGABgDAEQgDAGAAgLgAnSaFQgBAmALBBQAJA7ABAcQAAADAAACQCMAKB/AIQDOANAlgEQAAAAAAAAQAIAAAAgCQAAgFgBABQAAAAgBABQgCADgEAAQAEAAAEAAQEsAACVgDQEDgHB/gUQA2gIBZgCQBjgCAcgDQA2gHAdgSQAEgCADgDQAjgaAAg4QAAgGgFgXIgCgLQgBAFgBAFQgBAEgBADAm0dDQgEAAgGAAQgjgBhagEEAg1gAeQAGAAAOAAQAAALAAAJQAABhAECYQAPAAAgAAEAg/ADvQACAAAMAAQABA9ACBFIAAAAQABA7ACBCQAABKgHBvIAAABQgDAtgFAzQgGBIgDBHIAAAAQgGBmAABiQAAAoAFBGQAAAAAAAAQAFBYANCKQACAXADAVQAOCWAHAwQANgbAEgLEAhMAKnQAQAAATABEAh5AFuQgUABgVACEAhMAXbQACAAADAAQASAAARAAAT4cvQDMAiBxAIQAnADBvAAQB8AAAQgCQAtgGCPgqQAhgKARgaQAPgXAAgfQAGgZALgWIABAAQAAAHABAFEAg6ATNQAagBAbgBEAg7AOXQAbgBAWgC");
	this.shape.setTransform(-12.675,9.5897);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#003300").s().p("A73dsQjZgDiCgSIgZAAIgCkbIgDjPIAAiCIAChnIADhwQACh9AOiMQAHhLAWi0QAQiFAVkyQAYldAEgyQANiMBBijQAhhTAihPIADABIAAAAIgJAcIAJgcIAAAAQBdkHBKiEQB9jgDHiQQHwlnSVAAQGyAAKfI8QC0CZCuCvIANANIgCAHIACgHIA6BJIAFADIACABIABABIACABIABAAIABABIABABIABAAIAPAKIAGAEQBLAzA1BNIAAABIABAAQAVAgASAkIAFAJIAVAvQASArAUA5QAUBLAQBpIAAADIAAACIAHAuQAaC7AEBbIgUAAIAUAAIAAAUQAABhADCYIgNAAIANAAIADCCIAAAAIAEB9QAABKgIBvIAAABIgHBgQgHBIgDBHIAAAAQgFBmAABiQAAAoAEBGIAAAAQAGBYANCKIAAAsIAEAAQAOCWAHAwIAAAAQgLAWgHAZQABAfgPAXQgRAagiAKQiOAqgtAGQgRACh7AAQhvAAgogDQhwgIjNgiIgMgUIAIgFQAigaAAg4QAAgGgFgXIgCgLQAOhOAKhWQANh2AAhgQAAiQgOhaQgMhUgkhrQh8lLh8mPQhrlWm3iSQjYhIk8gdIhDgGQi+gOjgAAQiHAAhRAOQhdAQhIAoQh/BGjAD6QhJBehjB9QhDBYgaA+QgdBFgJBnQgHBVAADLQAAEeAjCjQALA0AeB6QAYBrAVB5IAJAxIAKAAIgKAAIgJgxIAFgBQAXAUAQAfQAVAoAAAnQAAAWgNA6IgLAtIgGAUIjIAAQAAgHgpADIgzAEIAAAHIgSAAIhdgBgAedr2Ig2g8IA2A8gEAhVgAeIAAAAgA9psKgAbHvbIAAAAg");
	this.shape_1.setTransform(-13.8125,9.5897);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#684619").s().p("AFIBcQgygpgIgzIACgCIAKgMIAAgKIBsAAQAwAZAzAEIBHAAIAAAKQgXAYgVA2QgYAqg+AAQg1AAgxgrgAEaAKIAAgYgAn9BVQgygLAAhAQAAgKAKg5QAIgyACgbIDSAAQATAEAsAGIAVAEIgEAaQgKAygHBBQgEArgIAKQgIAMgfABIhmgCIgsADIgPAAQgTAAgMgDg");
	this.shape_2.setTransform(-64.55,95);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#663300").s().p("AhGSKIkMgSIAAgGIAKAAIgKAAQAAgbgKg7QgKg+AAgmIAAgEIAAAEQAAAmAKA+QAKA7AAAbIh9gEQAAAKh7ABImCgBQhJAAhpACQhtAEgRADIAKgtQAOg6AAgVQAAgogWgoQgQgfgWgTIgFAAQgVh5gZhrQgdh5gMg1QgjijAAkeQAAjKAIhVQAIhnAehFQAag+BChYQBjh8BJhfQDAj7CAhGQBHgoBdgQQBSgNCGAAQDhgBC+APIBBAFQE+AdDXBIQG4CSBqFXQB8GPB8FKQAkBrAMBVQAOBZAACRQAABfgNB2QgJBWgPBOQgDgOAAgJIgEAAIAEAAQAAAJADAOIgCALIgBAHIABgHIACgLIADAMQAEAXABAFQAAA4gjAaIgHAGQgdASg2AGQgcADhjACQhZACg2AIQh/AVkDAGQiWADkrABIgBgFIgBABQgCADgFABIAJAAIgJACIgXABQg6AAihgKgAmGKEQABArALBsQAIBSABBIIAAATIAAgTQgBhIgIhSQgLhsgBgrIgBgiQAAi/A+lfQAijAAWj1QAUj4AMhjQASikAkhVQAnhcBIgsQAhgCAagJIARgHIAygVIgyAVIgRAHQgaAJghACIARgKIgRAKIgXAAIAXAAQhIAsgnBcQgkBVgSCkQgMBjgUD4QgWD1giDAQg+FfAAC/IABAigAh/B3IgKALIgCACQAIA0AyAqQAxAqA0ABQA+AAAYgqQAVg2AXgZIAAgKIAKAAIgKAAIhHAAQgzgEgvgZIhsAAgAu1AAQgCAagIAxQgKA7AAAKQAAA/AyAMQARADAdgBIAsgCIBmABQAfgBAIgLQAIgKAEgrQAHhCAKgyIAEgbIABAAIACAAIAXAHIgXgHIgCAAIgBAAIgVgDQgsgHgTgCIjSAAIAAgLIAAALIAAAAgAiRCAQgDAEAAAGIAAAPQABgGAGgKIACgFIgCAFQgGAKgBAGIAAgPQAAgGADgEQACgFABgEQgBAEgCAFgAh/BtIgMAAgAu1AAIgUAAgAlSRyIAAAAgAhMxNIAAAAg");
	this.shape_3.setTransform(-23.55,81.65);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgDABIAHgBQAAAAgGABIgBAAg");
	this.shape_4.setTransform(-5.9,198.6125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.hobbit_house1, new cjs.Rectangle(-230.9,-181.5,436.5,382.2), null);


(lib.paperplane = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_5
	this.instance = new lib.Symbol2();
	this.instance.setTransform(-864.95,-141,1,1,0,0,0,102.5,71.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({x:-845.5,y:-176.95},0).wait(1).to({x:-826.05,y:-211.4},0).wait(1).to({x:-806.6,y:-244.35},0).wait(1).to({x:-787.15,y:-275.8},0).wait(1).to({x:-767.75,y:-305.75},0).wait(1).to({x:-748.3,y:-334.2},0).wait(1).to({x:-728.85,y:-361.15},0).wait(1).to({x:-709.45,y:-386.6},0).wait(1).to({x:-690,y:-410.55},0).wait(1).to({x:-670.55,y:-433},0).wait(1).to({x:-651.15,y:-453.95},0).wait(1).to({x:-631.7,y:-473.4},0).wait(1).to({x:-612.3,y:-491.35},0).wait(1).to({x:-592.9,y:-507.85},0).wait(1).to({x:-573.45,y:-522.8},0).wait(1).to({x:-554.05,y:-536.25},0).wait(1).to({x:-534.6,y:-548.25},0).wait(1).to({x:-515.2,y:-558.7},0).wait(1).to({x:-495.8,y:-567.65},0).wait(1).to({x:-476.35,y:-575.15},0).wait(1).to({x:-456.95,y:-581.15},0).wait(1).to({x:-437.55,y:-585.6},0).wait(1).to({x:-418.1,y:-588.6},0).wait(1).to({x:-398.7,y:-590.1},0).wait(1).to({x:-379.3},0).wait(1).to({x:-359.85,y:-588.6},0).wait(1).to({x:-340.45,y:-585.65},0).wait(1).to({x:-321.05,y:-581.15},0).wait(1).to({x:-301.6,y:-575.15},0).wait(1).to({x:-282.2,y:-567.7},0).wait(1).to({x:-262.8,y:-558.7},0).wait(1).to({x:-243.35,y:-548.25},0).wait(1).to({x:-223.95,y:-536.25},0).wait(1).to({x:-204.55,y:-522.8},0).wait(1).to({x:-185.1,y:-507.85},0).wait(1).to({x:-165.7,y:-491.4},0).wait(1).to({x:-146.25,y:-473.45},0).wait(1).to({x:-126.85,y:-454},0).wait(1).to({x:-107.4,y:-433.05},0).wait(1).to({x:-88,y:-410.6},0).wait(1).to({x:-68.55,y:-386.65},0).wait(1).to({x:-49.15,y:-361.2},0).wait(1).to({x:-29.7,y:-334.25},0).wait(1).to({x:-10.25,y:-305.75},0).wait(1).to({x:9.15,y:-275.8},0).wait(1).to({x:28.6,y:-244.35},0).wait(1).to({x:48.05,y:-211.4},0).wait(1).to({x:67.5,y:-176.95},0).wait(1).to({x:86.9,y:-141},0).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-967.9,-663,1158.3,595);


(lib.Chimey_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.hobbit_house1();
	this.instance.setTransform(-55.1,66.5);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFCC").ss(1,1,1).p("AgJgHIABAAIADAAIAOAAQAAACADADQABABABABQAAAAAAACIAAAAIABAAIAEAAIAAACIAAAEAAOACIgOAAQgJgCgKgC");
	this.shape.setTransform(238.05,-206.5875);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#592F2F").ss(1,1,1).p("AHvp3QAABOATBsQAMBKAOA4QACAIACAHQABAAAAAAAogJGIAHAAIBxAAQBgAMB0AIIABAAQA1ADA4ADQABAAAAAAQBJADBOACQBiABBPADQCDAFBRAHQATABARAC");
	this.shape_1.setTransform(201.5125,185.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(1,1,1).p("AZs/FQAuiDAvh7QA2iQA4iEIA8AAQBIAVC/A6IABAAQAfAJAjALQD1BLA3AQQgSCEgTCFQAAABAAAAEAbTgi/QAxANCXAiQAAABABAAQgBBegBAsQgCBGgGAnQBJAPBXAUQA2AMAuAKQAAgGgBgGEAhNgi2QAIgkAOgxQATg/ABgzEAhPghoIAAANEAhPghoQAIACAIACQBxAZBLARIAAAAQBNASAmAKQALABALAEQAFACAGACIAKAGIAAAAIAEACIAGADEAmoggXQACABADABQAAAAAAAAQABAAABAAQAFACAEABQAHACAFABQgBACAAADQAAACAAABQACABAEgBIgGgDEAmqggPQAJADAKADQADABADABQgRBzgQBzQgLBOgMBPQAAAAAAAAQAAABAAAAQgPBsgQBtQABADAAAEQACAXACAfQAFBGAFAeQgFAAgPAFQgMAEgGABQgBAAgBAAQgHA1gIA1IAAABQgBABAAAAIAAAAQAAAEgBAEQgOBdgNBdQgDAVgDAUQgHAwgGAwQgBAAABAAQgIA7gHA7QgBABABAAQgNBlgKBmQgMBvgKByQgFA0gFA0QgJBygIBzQAAAzAEA4QAHBuAZCCQAZCFAqCbQAGAWAIAcQAAAAAAAAQADAKADAKQATBHAdBjQAAABAAAAQAAAAABABQAIAeAKAhQAQA6AOA0QATBMANA+QA3gBA8gBEAmOggeQABAAABABQAGABALADQADABAEABEAmQggdQAJACAHACQAFABADABEAhNgi2IACBOEAhFgiNQADgSAFgXEAecgiPQBMARBnAWAZs/FIA1AAQAvAHBBAMQA6AMBHAOAZl/FIAHAAAXp42QAAAAAAgBQAAgBABgCQAAAAAAgBQAXhJAXhHIBrAAQAxAIBHAJQAAAGAAAHAXp42IBoABQAvAEBkAOQACAAACAAQAIgJADgDAYL7LIANAAQAqiBAqh5AWt3GQAMADAMADQALACAMADAWd1ZQAEABAEABQAQg2AQgzQASg9ASg5AWU0aQAJgfAIgeQBvAaBZAVQCYAjBZAUQABAAAAAAIAAAAQAAgCAAgCIAKAAQgCACAAADQgHAOgJAQQgJANgIAOQgXAjgMANIADAFQACADAFABQABAAABAAQAEABAEAAQAAgEAAgFQADgTARggQAHgOAFgLQAHgTABgMQADABAFAAQA8ANAdAGQAeAFBBAJQgBAGgBAGATqqxQAqihApiUQAAAAAAgBQALgoALgnQAAAAAAAAQAOg0APgzIAAAAQAAAAAAAAQAJgiAKgiAU1w3QAKAAAOAAAYgveQAag1AoguQA1g8AUgeIAoAAQAdASAqATQAGACAGADIAAAAQABAAAAAAQACABACABQBMAgBzAlQgHAZgRAsQgPAsAAAiAU9vnICwAAQAXAEAcAFQBrASCjAfAV1ybIE2AAAXtquQAAA9gFBpQgEBYAAA0QgBALAAAKATqqxID5AAQAFABAEACQABAAAAAAQBHAUBaAXQAAAAABAAQBsAbCGAfQATAEATAEQAAABABAAQD/A5A+AAAR/kRQAOg8APg6QAAAAABgBQABgEABgEIAEALQCnAACaAJQCHAHB+APQAEABAEAAIABAAQAFAoAIBDQAGA4AAAtASfmQQAAgBAAAAQAmiVAliLARfjuQAGAmA8AxQBbBKAIAJQAQASA9BOQA7BJAOAOAYLifQgCA6APBWQAPBTACA0ICqAAIAeAAQBnASB7AJQACAAACAAIAAAAQBxAHBXgEASIkCQBQAdE2AyIAAAAQA5AKBAAJQBDALA6AIQAAABABAAQCNAVBQAKQABAAAAAAQBMAKAWAAQAUAAA0gmQAygkAIgQEAmMgcpQAFAAAKAFQAEACADABQAFACADAAEAhZgaWQAmhQAFgQQAVg4gDgxQBDAOA1ALQBRAQAuAHEAmLgaEIAaAAEAhZgaWQDUAUAxAGQACAAACAAQACgBACAAQADgCADgBQAKgFAFAAIAQABEAkXggpQAABQgBAnQgCA+gGAuAcJ+dIgEAAQgBAJgBAKQgIBMAACEQA+AIBQAIIAAAAQBBAHBNAHQAjADAfADAcJ+dQADgKAFgLAcH+IQAAgLACgKAcP+dIgGAAAbV4MQABgCACgCQADgGAIgIQACgDADgCQA0AHBCAKQA/AJBMALQAnAGAjAFIAAAAQDaAgBGACAZv0xQBbi4ATgkIAKAAAeH6ZQgRAigJAjQgGAUgIApAcvx+QAAABAAABQgDAJgBAEAc3yGQgGADgCAFAfqwqQAGACAFABQApANBlAdQAXgZAQgtQAQgsALgbEAgxgXlQAABJgGBPQgDAtgJBRQBFAKBvAMQAAgCAAgCIAFAAQAAACgBADQgCAGgIAKQAAABAAAAQgDAFgDAFQgBgKAJgFQAEgCAAgLIAAAAQACAAACABQAlAEArAEEAlZgUnQgCAQgDAQQAAAEgBADIAAABEAjHgSdQgEAJACAKQAHgRABgNEAlEgSVIAAABQACABABABQAHAFAIAFQAQALARAPEAkmgSoQAPAJAPAKEAlngXRQADAOACAZEAk0gK6QgOgGgPgFIAAgKAaPqDQAkhhAZg8QAuhzA0gaQApAIAtAJQAgAGAeAGIAAAAQECAyBQAWAelo5QAAA0gGA/QgCAZgMBcQByAOCeAUIAjAAQAHAHAJACQACABACAAQACAAADAAAbyllQBBAIBeAMEAiDgP9QA/ASBVAYAebGIQAzgBA3AAQA3gBA7AAIAAAAQAZAAAZAAIAoAAAXlGQIAAgFIC3AAQAXAAAYgBQAEAAAEAAIAAAGAebF8IAAAMIAAAcAeUWqQgOjSgIhvIAAAAQAAgBAAAAQAAgCAAgBIAAgBQAAgBAAAAQAAgBAAgBQAAgBAAgBIAAAAQgBgCAAgBQAAgCAAgBQAAgBAAgBQAAgBAAAAIAAmQIAAkYQAPABAPAAIAAAAQAzABA3gFQBMgJAmgSQAlCZAdC8QAAABAAAAQAPBdAMBmQBJgRBAAAAbTGKQBdgCBrAAAbTCCIAAEIAYxLWQAtgEBJgHQAigDAcgDIAAAAQBmgJAUAAAdfLGIAUAAAdVLGIAKAAAdLLQQAHAAANgKQACgCADgCQAAgBAAAAQACgCADgDAdfPUIAKAAIAAgKAc3PUIAoAAEAjHALkIBaAAIAAgKEAjHAOsQAHgBAGgCQALBcAKBlQAAAAAAAAQASgBAwgKQAjgHAYgGIABAAIAAgBQALgDAJgCEAk4ALpIATAAEAkZALpIAfAAEAk1ARMQARgGAfgCQABAAAAAAQAKgBALAAIAAAAQAOgBAQAAEAlnARSIAeAEEAjpARqQAFAxAFAzQgBAAABAAQBcAABqgCQAFAWADAUAbnPoIAAAeAbeRqQgBgBAAgBIAAAAQAAgEABgDIgBAAQgcAAgTABIgEAAQgEAAgFAAIAAhwAbdR0IABgKAbeR4IAAAAQAAgIAAgGAbeR4QgBgCAAgCQABA+AEBaQABARABAPQgBgZgBgdQgDhMgBgyAdBRqIAyAAAbeRhQAogBA6AAQABAAAAAAQAFAAAFAAIAeAAAbeRhQgBgLAAgKAbnWgIAAgLQAAAAAAgBIAAgNQAAgGAAgHIgDhOAaPWjQAlAAArACQAEAAAEAAIAAAAQByAFA7AAQAJAAAIAAAbnWHQAAhsgBgsQgChIgGgvAeBZ8QABgCACgBQAAAAABAAQAIgHAOAAAd9aGQAAgFAEgFActaGIAKAAQAGB9AJBFQAPByAAADQAtgBAtAAAaDaHQAygDAZgBQA0gDArgCQAFAAAGAAQAogCAhAAEAfKAjKQgKiQgJh+QAAgBAAAAQgMi2gKiTQgHhtgGhbEAkXAYYIAXAAIAHAAQBMAACSgEQAEAAAEAAQgBBGgFCGIAAAAQgFB0gICkQAAAGgBAGQgHB9gEBeQAAAAAAABQgHCTgBBEQgBAUAAANEAkSAa4IBpAAIAeAAQA2ASAaAOQALAGAhACEAjzATOQANCdAKCsQAAABAAAAQAAAAAAABQACAnACAoQACAoACAoQAGCNAECVIBfAAIABABQgBAJAAAAEAkDAa4IAPAAEAl7AbCQAGA8gCBVQgDBqAAAdIAAABQALAGA5AMQA3ALARAAEApeAYVQAYACALAEQgHAHgIAAQAIAAAIAAEAobAYEQAAAIAAAIQAogBAaACAbnPoQBQgDAogRAbnLaIAAEOAYpB4QAAAFAAAFAXaGUQgGgsgRhgQgUhvgBgNQAEgCAYgGQAdgHASAAIAAgFIAwAAAXeGSQAEgCADAAAXbGaQAAgFgFAAQABAAADgBQACgBABAAQABgBAAAAIgDADQgBgBAAAAAWxB4IBIAAAYILBQgBAHgBAIQAAAIgBAKQANACAFAAAYDLVIAAAKIgTAAQAIAAAMADQABAAAAAAQgCAggCAuQgDA+AAAMQAABKAAABQAAAIABAIQABAKADAHQAFARAKAAQAfAAAdgJQAKgEAIgCQASgFAOAAAYGLQIgDAFQgZAAgFAFIAAlKAZgPoQAcAAAlABIAAAAQAIgBAIABQAdAAAZgBAYIR+QgBgMgBgNQgDgyAAhNAX5RlIANAAIAgAAQAFABAGAAQACAAACABQAVACAcAEQAnAFAbACAYHWXQAAgSgCgfQgCgoAAgEQAKh2AAg8IAFAAAahRqIAAgIQg8ABgwAEAY0PoQATAAAZAAAYHWXQABgBABAAAYBWmQAAAAAAAAQAKAAAOgCQAAAAABAAQAEAAAEgBQADAAACAAQAaAAAGACQAIABAhAPAYKWfQgCgDgBgFAXxWnQAGAAAKgBQgBA2gPBvQgHA0gEAnQgFAuAAAbQAAAkATC6QAGBAAJBSQAGA4AHA9IAcAAIASAAQABAAADAAQATADBXAQQBQAQAngFAX5WbQAFgCAJgCAZrWiQAFADAGAEAZbWYQACABADACQAFADAGAEQAMAAAMAAIACAAQACAAADAAIAAAAQAAgBAAgBIAFADAZXWhQAKAAAKABAaHWsQACgFABgEQgBAAABgBQACAAADABAaGW3QAFADAEAEAYnWjQATgBAVgBAYkaNQA3gDAogDIAAAJAXmamQAdgPAtgCQBOgFAAAAAaDW7IAADMEAYQAjUQAAACAAADQAJBTAJBcQABAJACAJQACAaADAcEAYsAjUQALAAALAAQBxAAA4gBQAEAAAEAAQgBABAAAAQgBAFAAAFEASgAnOQBPgCCNgXQAVgDBagNQAjgGAXgFQABAAABAAQAAAAAAAAQAegHAJgGEASgAnOQAAgFgBABQgCAEgGAAQAEAAAFAAgEALAAmhIBGAAQFeA1AzgFQAAAAABAAQAIgBAAgCEgfQAl5ID1AAQC+AIChAMQCgAOBWAGQErAUKbAAQDNAAFLgRQEKgPBdgCQABAAAAAAQAWgBANAAEAkXAfaIAFAAQADB/ABCEQAAABAAAAQABBUAABWAa/fGQABADABAEIAhAAAX0fNIDLAAIACAAQAmCCACAIQAPBEgFA4QBAgCA1gCIABAAIABAAQAfgCAcgCQAFAAAFgBIAbAAAYnfEQBKgEBOgBQBJgCBNAAEAdpAjeIAAC0EAfXAmcQgHhtgGhkQAAgBAAAAIANAAIAAgKEAkrAjeIDIAAAfhhjQAACVgKBaEgnEAAKQgFBAgUBfQgLA3gaB8QgvD+AFElQADD2gQEDQgHCFgKCJQgLGEgEBZQgOETgaAhICpAAQA+gSAagFQAmgHBUAAQAsAABLAIQBLAHAYAAQAEAAAogFQApgFARAA");
	this.shape_2.setTransform(-9.35,0);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#663300").s().p("Ah7QJQhPgChJgDIAAgGIgNjRIAAgBIANAAIAAgKIAAAKIgNAAIgTkOIAAgBIgWlJIgNjIIARAAIgRAAIgWk/IAAgBIAAgBIAAgDIAAgBIAAgBIAAgCIAAgCIAAAAIgBgDIAAgDIAAgCIAAgBIAAmQIAAkYIAeACIAAAAQA0ABA2gGQBMgJAmgSQAlCZAdC9IAAAAQAPBeAMBlIgNADIANgDQAMBdAJBkIAAAAIAJBkIAAAAQBcAABqgCIAIAqIgIgqIBzgCQAABOATBsQAMBJAOA4Ig+AOIAAgQIAAAQIgIAAQiSAEhMAAIgHAAIgkAAQgKisgNidQANCdAKCsIAAAAIAAABIAEBPIAEBQIgPAAIAPAAQAGCNAECVIgFAAIAFAAQADB/ABCFIAAAAIABCqIgBAkIiwgFgAkgMsgAEwB2IAAAAg");
	this.shape_3.setTransform(218.9375,143.7625);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#666666").s().p("EACjAmVIhugFIABgKIAAi0IAAgQIAAAAIA8gDIAKgBIAaAAIAAAAIAODSIAAAFIgBABIAAgBgEALAAjSIjIAAIgLAAIAAgBQgBiEgDh/IBfAAIAAAAIAAAKIAAgKQAMAHA5AMQA3ALARAAIgBALIgLDbgEgD1AjHIgRAAIgcAAIgNh1IgPiSIDLAAIACAAIAnCLQAQBDgGA5IgHAAIipABIgFgBgAJIfOIhfAAQgEiVgGiNIBpAAIAAAKQAGA8gCBVIgECHIAAAAgAHpfOgAk+fAQgSi5AAgkQAAgbAEguQAdgPAtgDIBOgFIAFAAIAAgIIBLgFIBfgEIhfAEIhLAFIAAjNIACgCIABgCQADgDgBgDIgBgEIADgJIAAgBIAEAAIBRADIAIAAIgIAAIhRgDIgEgCIAAACIAAAAIgFAAIgCAAIgYgBIgLgHIgFgCIgCAGIgCADIgFABIgDgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAAAIAAgBQgFACgLAAQgUgBgKADIgGACQgEABgCgBIgCgCIgBABQgEADgDgFIgBgKIgCABIgCgwIgCgtQAJh1ABg8IgGgKIgBgZIAfAAIAMABIAEAAQAwgDA8gBIAAhwIBGgKIAAAeIAAgeQBOgEApgQIAKAAIAAgKIAAAKIgKAAIgoAAIAoAAQgpAQhOAEIAAkOIgBgVQBkgJAUAAIAFAFIAAAAIgGAFIgJAAIAJAAQgMAKgHAAQAHAAAMgKIAVAAIAKAAIAAGQIAAAAIAAACIAAADIABADIAAABIAAABIAAACIAAACIAAAAIAAAEIAAABIAAAAIgLABIgyAAIhiAAIgBgCIAAAAIAAgCIABgFIBhgBIABAAIAKAAIAeAAIgeAAIgKAAIgBAAIhhABIgBgVIABAVIgBAAIgvAAIgEAAIgJABIAJgBIAEAAIAvAAIABAAIgBAFIAAACIAAAAIABACIgBAKQABA9AEBaIACAhIADBNIAAAOIAAANIAAABIAAALIAAAFIAAAAQBxAEA7ABIANDHIgGABQgOAAgJAGIAAAAIgDAEIhJABIgKABIAAAIIAJAAQAGB8AJBGIAPB0IiVADQhOABhKADQBKgDBOgBIAAAHIAAAGgAikWyIgIgIIAIAIgAkhR8IgEAAgAjMRgIBCAIIhCgIIgxgGIAxAGgAiRReIAAgIgAhzezgAHkYMIgNAAIAAgBIAkABgAG2RdQgKhkgLhcQBJgRBAAAQhAAAhJARQgMhmgPhdIAAgBQgdi8gliZQgnAShLAIQg3AGgzgBIAAAAIgegBIAegKIAAgdIBqgBIByAAIAAAAIAyAAIAoAAIAQgEQAZCGAqCaIAOAyIAAABIAGAUIAwCqIAAABIAAAAIASA/IAfBvIgeAAIgBAAIgUACIgBAAQgfACgRAGQARgGAfgCIABAAIAUgCIABAKIgUAFIAAAAIgBAAIg7AOQgxAJgRACIAAgBgAIFLdIggAAgAHuLYIAAgKIAAAKIhaAAIBaAAgAhUReIAAAAgAhURVIAAAAgAhURVgAAsPIgAArK6gAlvD8IgWh8QAEgCAZgGQAdgHARAAIAAgFIhIAAIAAAAIADACIAPAAIAHACQAEADgDADQgJADgOAAQAAACgEADIgEADIgEADQgEABgBgFQgBgDADgEQAAAAgBAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAIAGgEIAGgDIABgBIgSgEQgPgOg5hKQg+hNgRgSQgHgJhbhKQg9gxgFgmIAngTIABgBQBRAdE2AyIgDAUQgCA6APBWQAQBSABA1IgxAAIAxAAIAAAKIAAgKICqAAIAAAKIAAEIIgIAAIgvABIi4AAIAAAFIgGACIgBAAIgDABQgGgsgRhfgAkJBsgAkJBsIAAAAgACwh5IgBAAQhQgKiMgVIgBgBIABgIQAAgtgGg4IgOhrICfAUIEQAiIAzAJIADABIgJBoIgHAAQgIAQgyAkQg0AmgUAAQgWAAhMgKgAhBlxIAAAAIgJgBQh9gPiIgHQABg0AEhYQAFhpAAg9QBHAUBaAXIAAAAQBtAbCFAfIAmAIIAAAAIgCAIQAAA0gGA/IgOB1IifgUgAhBlxIAAAAgAikqPQhagXhHgUIgBgBIgJgCIj6AAQArihApiUIAAgBIAWhPIAAAAIAchnIAAAAIABgBIAThDIAQg5IASg9IAghpIAkh3IBoACQAvAEBkANIADABIgEAFIgMANIAGAEQgTAkhbC4IgCAIIDwA4IABAAQgBAMgIATIgRAbQgVAjgMANIADAFQACACAFABIACABIAAACIgFAMIgDgBIgBAAIAAAAIgMgGQgqgTgdgRIgoAAIk2AAIE2AAQgUAeg2A8QgoAugZA1QBrASCjAfQg0AaguBzIg+CdIAAAAgAlFvzIAzAJIgzgJIiwAAgAjF01IjIguIDIAugAlX3HIgWgFIAWAFgAhd4YIACgFIgCAFgACPucIABgHQAAgiAPgsQARgsAHgZIALADICOAqQAXgZAQgtQAQgtALgbQAHgQABgNQAIgKACgHIBQAJIgBAIIAdATIAAABIAAABIAAAAIgBAIIgbC6IgHApIgMBgQhQgWkCgygAHkvfIiUgqICUAqgAiHyngAhL4vIALgMIgLAMIgDgBQhkgNgvgEIhogCIAAAAIABgDIAAgBIAuiQQAqiBAqh5IA1AAQAvAHBBAMQgFALgDAKIgEAAIgCATQgIBLAACFQhHgJgxgIIhrAAIBrAAQAxAIBHAJIAAANIAAgNICNAQIgCARQgRAigJAjQgGAUgIApIgBAFIh2gRgAhL4vIAAAAgAIq6IQgwgGjUgUQAmhQAFgQQAVg4gDgxIB3AZIh3gZIgBgMIABAMIhkgWIiggjQAGgnAChGIABiLIC0AoIgChOQAIgkAOgxQATg/ABgzIADgMIABABIBBAUQD1BLA4AQIglEJIAAAAIgMgCIgCgCQgCgDAAgCIgQAAQgLgEgLgBQgmgKhNgSIAAAAIi8gqIgQgEIAQAEIC8AqIgEARIgBB3QgDA+gGAuQBSAQAtAGIgBAHQAFAAALAFIAHADIgXCdIgQgBQgFAAgKAFIgGADIgFABIgEAAgEAEcghnIAAgNg");
	this.shape_4.setTransform(174.95,1.2254);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFCC").s().p("EAHTAm8IABgjIgBiqIALAAIDIAAIAJAAIAAABQgHCUgBBDQhRgGiDgFgEAAbAmtQhzgIhggMIhxAAIgTivIAygFICpgBIAIAAQBAgCA1gCIAAAAIAAAPIAAC0IAAAKgEgA9AkEIASgBIAAAAIACAAIgCAAIAAAAIgSABIAAAAIgEAAQgegBgsgHIgEgBIgGgBIgCgBIgGgBIgDAAIhqgTIBqATIADAAIAGABIACABIAGABIAEABQAsAHAeABIAEAAIAAAAgEgBaAjlIgBAKIABgKIABgBIgBABgEgBjAhoIgoiLIAhAAIghAAIgCgGIAAgHICVgDIgOh0QgJhGgGh8IgKAAIAAgIIALgBIBIgBQgEAEAAAGQAAgGAEgEIAEgEIAAAAQAIgGAOAAIAHgBIAVFJIgIACIAIgBIATEPIgbAAIgKABIg7AEIgBAAIAAAAQg1AChAACQAFg5gPhDgAAIfNIBaAAIhaAAgEAAcAjggAJzf+Qg5gMgLgHIAAAAIADiHQAChVgGg8IAAgKIhpAAIgEhRIgEhOIAAgBIANAAIAXAAIAHAAQBMgBCSgEIAIAAQAABHgGCGQghgDgLgGQgagOg2gRIgeAAIAeAAQA2ARAaAOQALAGAhADIAAAAIgNEYQgRAAg3gLgALIbxIAAAAgAlbZcQAPhwABg1IAAAAIAYgCIABAAIAJgBIAEAAQAbAAAFABQAIACAhAPQghgPgIgCQgFgBgbAAIAogCIAEABIAEgBIAUAAIALAHQACgBAGAAQAFAAACACIACACIABABIABAEQAAADgCADIgCACIgCACIAADNIhfAGIBfgGIAAAIIgFAAIhOAFQgtADgdAPIALhbgAhlW2IAAAAIAAgFIAAgLIAAgBIAAgNIgBiZQgChIgGguIAAgBIAAgNIBjAAIAxAAIALgBIAWFBQg7gBhxgEgAGmTfIgKhkQASgCAwgJIA7gOIABAAIAAAAIAUgFIAAgKIAAAAIAeAAQATBMANA+QhqAChcAAIAAAAgAI4RnIgegFgAkbR3IgLgBIggAAQgDgzAAhMQAFARAKAAQAgAAAcgKIASgFIBBAAIAAAAIAQAAIA2AAIhGAKIAABwQg8ABgwADIgEAAgAk6QIQgKAAgFgRQgCgHgCgLIgBgPIAAhLIADhLIAEhOIABgRIACgPIgCAPIgDAFQgZAAgFAFIAAlKIAAgFIC4AAIAugBIAIAAQBdgCBqgBIAAAdIgeAKIAAEYIgKAAIgUAAIAFgFIAAAAIAFgFIgFAFIgFgFQgTAAhlAJIAAAAIg/AGIh2ALIB2gLIA/gGIAAAAIABAVIAAEOIg2AAIgQAAIAAAAIhBAAQASgFAOAAQgOAAgSAFIgsAAIAsAAIgSAFQgcAKggAAIAAAAgAk1L1IgSgDIASADgAh5GhIAAgGgAhlP5gAjsP5IAAAAgAlJP3IAAAAgAh5CTIAAgKIiqAAQgBg1gQhTQgPhVACg6IADgUQk2gyhQgdIgJgPIAdh2IABgBIACgIIAEALQCnAACaAJQiagJinAAIgEgLIAAgBIBLkgID5AAIAJADIABAAQAAA9gFBpQgEBYAAA0IgBAVIABgVQCHAHB+APIAIABIABAAIANBrQAGA4AAAtIgBAIIh9gTIh5gTIAAAAIAAAAIB5ATIB9ATIABABQCMAVBQAKIABAAQBMAKAWAAQAUAAA0gmQAygkAIgQIAHAAQgJBygIBzQAAAzAEA4QAIBtAYCCIgQAEIgoAAIgyAAIAAAAIhyAAIhqABIAAgLIAAALQhqABhdACgAERCoIA3gBIAKAAIgKAAIg3ABIAAAAIAAAAQg8AAhGgEIgFAAIAAAAIgEgBQh6gIhngSIgeAAIAeAAQBnASB6AIIAEABIAAAAIAFAAQBGAEA8AAIAAAAIAAAAgACKCdQAKhaAAiVQAACVgKBagABOGYgAGIkVQgKgCgHgHIgjAAIkQgiIAOh1QAGg/AAg0IADgIIgBAAIgmgIQiFgfhsgbIA9idQAuhzA0gaQijgfhrgSQAag1AoguQA1g8AUgeIAoAAQAdARArATIALAGIABAAIAAAAIAEABIAEgMIAAgCIAIABIAAgJQADgTARggIALgZIAQgeIACgFIgKAAIAAAEIgBAAIjwg4IACgIQBbi4ATgkIgFgDIALgOIAFgFIB1ARIABgFQAJgpAFgUQAJgjARgiIACgRIAAAAICOAOIBCAGIhCgGIiOgOIAAAAIiNgQQABiFAHhLIAEACQAAgLACgKQADgKAFgLQhAgMgwgHIg1AAQAuiDAvh7QA2iQA4iEIA7AAQBIAUC/A6IgDAMQgBAzgTA/QgOAxgIAkIACBOIizgnIgBgBQiWgigxgNQAxANCWAiIABABIgCCKQgCBGgGAnICgAjIBkAWQADAxgVA4QgFAQgmBQQDUAUAxAGIAEAAIAEgBIAGgDQAKgFAFAAIAQABIAAAAIAAABIgfDZIABAHIAEA2QAFBGAFAeQgFAAgPAFQgMAEgGAAIgCABIAAgBIABgHIAFggIgFAgIgBAHIAAABIgPBqIgegTIABgIIhQgIIABgFIgFAAIAAAEQAAAKgEADQgJAFACAKQgFAJACAJQgLAbgQAtQgQAtgXAZIiOgqIgLgDQhzglhLghQBLAhBzAlQgHAZgRAsQgPAsAAAiIAAAHQEBAyBQAWIAAAAIgPB2IAAABQgNBkgKBnQgMBvgKByIgDgBgAGYn2Qg+AAj/g6QD/A6A+AAgAA3uLIA+AMIABAAIgBAAIg+gMIhVgRIBVARgAGGyoIi0gWIC0AWgADQyyIACgMQhBgJgegFIhZgTIBZATQAeAFBBAJIgCAMgADe08QgDAtgJBRQAJhRADgtQAGhPAAhJQAABJgGBPgAIf2ZIgFgnIAFAngACc3tIBKALIAAAAQDaAgBGACQhGgCjaggIAAAAIhKgLIiLgUICLAUgAhl38IgKAAgABF+HIiAgaICAAagAg9+MIgGAAgEAD4gh8QADgSAFgXQgFAXgDASgACdwZIAAAAgAJO8TQgKgFgFAAIABgGQgugHhRgQQAGguACg+IABh3IAEgRIABAAQBMASAmAKIADAAIAQAFIAHACIAFABIAAABIACAAIAKAGIAAAAIgPAAIgTgFIATAFIATAGIAGACIghDmIgHgDgEABPgh+IAAAAg");
	this.shape_5.setTransform(177.525,-1.675);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.instance}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Chimey_1, new cjs.Rectangle(-285.5,-253,546.2,519.7), null);


// stage content:
(lib.holterman_background = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// chimney_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.1,1,1).p("AUjAHIBBAAQDJAqB6AkQC4A1BsBAA4JjAQACgSCKAUQC6AcA7AAA4Ji/QgCABAAADQACALAAgPgA4JjAQADAAACAAQgDAAgCABQAAAAAAgBgA+8h1IgFAAQAAADgDACQgEAEgCABQBcAIAygcQAvglAegSQAqgXBCAEQAmACBUAH");
	this.shape.setTransform(199.05,228.6704);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// paper_plane
	this.instance = new lib.paperplane();
	this.instance.setTransform(-161.15,452.7,1,0.5467,0,0,0,-864.2,-140.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// hobbit_house
	this.instance_1 = new lib.hobbithouse_2();
	this.instance_1.setTransform(206.6,182.3);

	this.instance_2 = new lib.Chimey_1();
	this.instance_2.setTransform(261.05,397.75);

	this.instance_3 = new lib.CachedBmp_1();
	this.instance_3.setTransform(-32.9,206.35,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3},{t:this.instance_2},{t:this.instance_1}]}).wait(1));

	// smoke
	this.smoke = new lib.smoke();
	this.smoke.name = "smoke";
	this.smoke.setTransform(472.3,314.05,1,1,0,0,0,0,102.7);

	this.timeline.addTween(cjs.Tween.get(this.smoke).wait(1));

	// sky
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().ls(["#0097CA","#ECFFFF"],[0,1],-481.9,0,482,0).ss(0.1,1,1).p("EhLSgyFMCWlAAAMAAABkLMiWlAAAg");
	this.shape_1.setTransform(475.275,320.65);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#0097CA","#ECFFFF"],[0,1],-481.9,0,481.9,0).s().p("EhLSAyGMAAAhkLMCWlAAAMAAABkLg");
	this.shape_2.setTransform(475.275,320.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(215.1,319.1,768,345.4);
// library properties:
lib.properties = {
	id: '03DAA6ED39D6D147B221C7A949E9A74A',
	width: 960,
	height: 640,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/holterman_background_atlas_1.png?1770872917038", id:"holterman_background_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['03DAA6ED39D6D147B221C7A949E9A74A'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;