(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"cryptids33_atlas_1", frames: [[0,0,1428,435],[0,437,1428,435],[0,874,1415,420],[0,1296,1415,420],[0,1718,1526,318]]},
		{name:"cryptids33_atlas_2", frames: [[0,372,882,65],[0,0,1192,184],[0,186,1192,184],[1621,0,140,128],[1763,0,131,124],[1194,0,182,259],[1378,0,241,183]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.CachedBmp_12 = function() {
	this.initialize(ss["cryptids33_atlas_2"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_11 = function() {
	this.initialize(ss["cryptids33_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_10 = function() {
	this.initialize(ss["cryptids33_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_9 = function() {
	this.initialize(ss["cryptids33_atlas_1"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_8 = function() {
	this.initialize(ss["cryptids33_atlas_1"]);
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_7 = function() {
	this.initialize(ss["cryptids33_atlas_2"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_6 = function() {
	this.initialize(ss["cryptids33_atlas_2"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_5 = function() {
	this.initialize(ss["cryptids33_atlas_2"]);
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_4 = function() {
	this.initialize(ss["cryptids33_atlas_2"]);
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_3 = function() {
	this.initialize(ss["cryptids33_atlas_2"]);
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_2 = function() {
	this.initialize(ss["cryptids33_atlas_1"]);
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_1 = function() {
	this.initialize(ss["cryptids33_atlas_2"]);
	this.gotoAndStop(6);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Title = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_12();
	this.instance.setTransform(-220.5,-17.45,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Title, new cjs.Rectangle(-220.5,-17.4,441,32.5), null);


(lib.righteye = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,1,1).p("AAFAAQAAACgBACQgCABgCAAQgCAAgBgBQgBgCAAgCQAAgBABgCQABgBACAAQACAAACABQABACAAABg");
	this.shape.setTransform(-0.5,-0.575);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1.5,1,1).p("AAPAAQAAAGgEAFQgEAEgHAAQgFAAgFgEQgEgFAAgGQAAgGAEgEQAFgFAFAAQAHAAAEAFQAEAEAAAGg");
	this.shape_1.setTransform(-0.425,0.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgKALQgEgFAAgGQAAgFAEgFQAFgEAFgBQAHABAEAEQAEAFAAAFQAAAGgEAFQgEAFgHAAQgFAAgFgFgAgEgNIgBAFIABADQABAAAAABQAAAAABAAQAAAAABAAQABAAAAAAQAAAAAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAgBQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAAAgBgBQAAAAgBAAQAAAAAAAAQAAAAgBAAQgBAAAAAAQgBABAAAAQAAAAgBAAg");
	this.shape_2.setTransform(-0.425,0.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("A7pE/IAAgDIAAgFQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBgBAAgAbeksIgCAAIgDAAIgCAAIgCAAIgCAAIgCAAIgCAAIgCAAIgCAAIgCAAIgDgBIgCgCIgBgBIgBgCIAAgBIAAAAIAAgDIAAgBIAAgCIABgBIAAgBIACgCIABgBIABgBIADgBIACAAIAEAAIAEAAIADAAIAFAAIACAAIAFAAIABABIABAAIAAAAIABAAIAAABIABAAIAAAAIAAAAIAAABIABABIAAAAIABABIAAABIAAAAIAAABIABAAIAAABIAAAAIAAABIAAABIAAABIAAABIAAABIgBABIAAABIAAABIgBAAIgBABIAAAAIAAAAIAAABIAAAAIAAAAIgBAAIAAABIgBAAIAAAAIgBAAIAAABIgCAAIgBAAg");
	this.shape_3.setTransform(176.05,-32.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.righteye, new cjs.Rectangle(-2.9,-64.1,356,67.1), null);


(lib.reedsAndLake = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// animation
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000066").s().p("AgKKOQgcgKgPgcQgPgcAIgcQACgIAHgOIAJgVQAFgOADgbIAAgEQAGg8AAgfIgCgtIgTgBIgFgCQgTgFgOgMIgHgHQgIAMgMAJIgEgTQgGgWgVglQgqhJgbgjIgBgBIABgFIAAgBIgFABIgSgWIgVgbQgRgRgagEQgIgCgJABIAAgRIgBgZIgDgYQgBgJgCgDQgBgCgKgGQgRgJgKgSQgKgRAAgTQgBgUAKgRIAHgLQA2AwAyA1QARATANAJQASALAXAAQAYABATgLQATgKALgUIAFgLIgLgHQgTgNgPgcIgWgwQgLgWgDgIQgJgYAAgcQAAghAKgSQAHgPAMgJIALgIIAGgDQADgKAIgKQAIgLAKgHIgJggIgKgnQgHgWgEgGQgHgNgUgSQgWgTgHgKQgMgSgBgVQgBgWAKgTQAKgSATgLQAOgIAPgDIALgBQAcAAAdARQAFgKAJgJQASgSAXgEQAYgEAWALQAXALAMAUQAFAJAFANIAFAQQAJgGAMgDIACAAQAIgLAKgIQAUgNAagBQAZAAAVANQAIAFAIAHIACgMQAGgSANgNQAOgPARgGQASgHAUABQAUACAQALQAOAJAJAOIADAFQAKARAAAUQAAALgGAbQgFAZACAOIABAHQAWAFAQAOQAIAIAOAVQAbAoAJAXQAJAXADAeIAHAFIAJgHQAUgOAbABQAWAAARALIAIAFQAOALANAWQAQAbATA9QAOAsADAWQACAQAAAXIAAAmIAAAgQAAASgEANQgHAWgVAQQgUAPgYACIgCAAQgHANgLALIgCACQgSAOgUAEQgXAEgWgKQgWgKgMgTQgMgRgIgoIgBgHIgDgLIgUhkQgJgtgKgVQgEgKgHgJQgVgGgRgRQgMgNgFgOQgDgIgBgJQgBgHAAgRQAAgPgCgIQgBgHgEgJIAEAiIAFAtQAEAkAAAaQAAAqgNAXQgFAKgIAIIAWAdIASAdQAFAIALAXQAJAUACAJQAEAUgHAUQgHAUgPANQgPAOgUAEIgDABIAUAfQAPAXAOALQAOAMASAFQALADALAAQgEATACATQAAANAEAMQADgJAFgJQAKgPAPgKQAggUAkAIQAWAEAeATQAPAJASANQAaASAMANQAIAKAKAQQAQAbAEAYQAGAcgKAZQgJAVgUANQgUAOgXAAIgBAAQgXAAgUgNQgQgJgKgOQgLAWgXAMQgZANgbgFQgagFgTgWQgNgPgEgSIgCgQIAAgSQgGAOgNAMQgTARgYADIgBAAQgZACgXgMQgWgMgMgWQgGgNgEgTIgGghQgCgKgFgPQAKgKAGgNQAJgYgEggQgCgPgLgpIgFgYIgDgbQgEgUgOgQQgOgQgUgHQgTgGgVAEQgJABgIAEIgEgGIgTgZIgMgNIgCAAQgWAGgXgHQgWgHgOgSIgHgJQgLAHgMADIAABMQAAAtgBAXIgBAOQAIgCAIABQARABAQAIQARgGAVADIAPAEIACAVIAGAUIAFAVQAFApAIATQAJAVAVAOQAJAGAKADIABAKIACApIABAOQACA9gHA9QgFAlgHAlQgIAogNAUQgPAWgZALIgFACIgIADQgMADgLAAQgNAAgNgFgAAbkqQAWAdATAoQAPAdATAxQAKAXADANQAGAVgDARQgCAXgQASIgOAOQAIAMAOAJQAUAMAWAAQARAAAPgHIgLgMQgUgVgGgNQgMgWAEgaQAEgaARgSQARgRAagFIAMgBIgjhkIgPgqQgJAGgKAEQgUAIgXgEQgWgEgSgNQgMgLgIgNQgFAQgJAMgAAbmjIAAgHIgCAAIACAHgAnJAZQgZgCgTgOQgPgLgMgXQgEgFgQgjQgOghgohFQgKgQgGgFQgHgGgRgJQgQgLgJgUQgIgTACgVQADgTANgRQANgRASgJQASgIAVAAQAVgBASAIQAaALAWAZQAQARATAgQAgA1ArBZQAOAbADATQAEAXgLAXQgLAVgVAMQgSALgWAAIgFgBgAj7k1QgSgHgTgTIgeghQgcgeg4gpQgUgOgJgEIgegLQgUgIgMgSQgNgSgCgVQgCgVAKgUQAIgPAMgKIAIgGQASgMAYgBQAWgBAWAHQAXAIAiAWIAeAVQBEAxA4A+QASAVAHANQAKAWgEAZQgEAYgQASIgKAJQgNAJgSAEQgIACgJAAQgPAAgOgGg");
	this.shape.setTransform(-151.0276,-111.4425);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0099CC").s().p("AqrJ7QgSgJgMgOIgGgIQgMgTAAgZQABgZAOgTQAFgHALgJIARgRQAKgNAKgSQAbgyAKg4QAKg4gIg5IgHgwQgCgcAHgTQAHgUARgOQARgPAVgDQAVgDAVAJQAUAJANARIAGAJQAHgGAJgFQASgIATAAQALAAAMAEIANAEQASAIANAPIAOATIANATIAWAeQAJANAJAVQAJATAHARQAVA1gOAkQgCAHgEAHQgIAMgMAJIgBABQgTAOgWACQgXABgVgLQgVgLgLgUQgEgJgEgMIgHgWIgGgQQgJgXgPgUQABA3gEAdQgKBWg7BnIgCADQgWAmgTATQgdAdggAEIgMABQgRAAgQgHgAisImQgRgCgQgLQgPgJgJgNQgEgGgDgHQgIgRAEgZQAAgIAJgkIAAgBQAJADAJAAQAUAAASgKQASgJALgQQARgbgEgiQAMgJAIgMIAHAHQAOAMATAFIAGACIgBAfIAAAiQAAAUgCANIgFAhIgCAGQgFAWgEALQgMAbgWAOQgTANgWAAIgLgBgAJpHsQgWgKgLgUQgEgIgDgLQAXAAAUgOQAVgNAJgVQAJgYgFgdQgFgYgPgbQgKgQgJgJQgMgOgagSQgSgNgPgJQgegTgVgEQglgIggAUQgPAKgKAPQgFAJgDAJQgDgMgBgNQgBgTADgTQgLAAgLgDQgSgFgOgMQgNgLgPgXIgVgfIADgBQAVgEAPgOQAPgNAHgUQAHgUgEgTQgCgJgKgVQgLgXgFgIIgSgdQAWABATALQAOAIAVAXQARASALAOIABACIAGgEIACAJQAIAnALAQQANATAWAKQAWAKAWgEQAVgEARgOIAAABQACAJABAMQAQgBAQAFQAbAKAhAlQAiAnASAdQAZAoAFAmQACAQgBAZIAAApIABAmQAAAMgCAKQgBAJgCAHQgHAWgTAOQgSAQgWACIgJABQgSAAgRgJgABsEhQgKgDgKgGQgUgOgJgVQgIgTgFgpIgGgVIgFgUIgCgVIgQgEQgTgDgSAGQgQgIgSgBQgIgBgIACIABgOQACgXAAgtIAAhMQAMgDALgHIAGAJQAPASAXAHQAWAHAWgGIABAAIAMAOIATAYIABAIIAEgCQAHgEAJgBQAVgEAUAHQATAGAOAQQAPAQADAUIADAbIAFAYQALApACAPQAFAggKAYQgFANgKAKQgGAHgIAFQgVAOgXAAIgDAAQgLAAgKgEgABagJQgOgJgJgMIAPgOQAPgSADgWQACgSgFgVQgEgNgJgXQgUgxgOgdQgUgogWgdQAKgMAFgQQAHANANALQARANAXAEQAWAFAVgJQAKgDAJgHIAPAqIAiBkIgMABQgZAFgSARQgRASgEAaQgDAaALAWQAHANAUAVIALANQgQAGgQAAQgWAAgUgMgAHNlUQgEgegJgXQgJgXgagoQgOgUgJgJQgPgOgWgFIgCgHQgCgOAGgZQAGgbAAgLQAAgUgKgRIgDgFQAPgJARgCQAUgBASAHQASAIAMAPQAKASAGAIIAQASQAOARANAUQAVAhAUAwQAOAjAEAaQADAZgGAUQgRgLgWAAQgbgBgVAOIgIAHIgHgFgAAHmyIABAAIABAHIgCgHg");
	this.shape_1.setTransform(-149.176,-110.6496);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0066CC").s().p("Al/HYQgbgCgTgRQgSgQgHgaQgFgVAEgUIACgIQAEgMALgUQAOgXADgIQAOgfgDgkIgHgmQgFgWACgPQACgVAOgSQAFgHAHgFIAFAPIAHAWQAEANAFAIQALAUAVALQAVAMAWgCQAXgCATgOIABAAQABAOAAASIAAAqIAAAfQgBASgDANQgDANgPAeIgRAhIAAABQgLAWgIAKQgMASgOAJQgSALgVAAIgIAAgAD4FSQgigEgVgdQgPgWgBgaQAAgIABgHIADgQIABgPQAAgMgHgVQgMgigHgRIgCgoIgBgKQAMAEANgBQAXAAAUgOQAIgFAGgGQAFAOACAKIAGAiQAEATAGAMQAMAWAWAMQAXANAZgDIABAAQACAOAAAMIAAAEIgEAkQgFAggKAQQgQAagiAIQgJACgKAAIgHAAgAGpj/QgUgWgPgJQgSgLgWgBIgWgcQAIgIAFgLQANgXAAgqQAAgZgEgkIADAAQAFAPAMAMQARARAVAGQAHAKAEAKQAKAUAJAtIAUBkIgFANQgKgNgSgTg");
	this.shape_2.setTransform(-153.7012,-89.3555);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AmlDBIkQAAIgggBQgSgCgNgHQgTgIgNgTQgMgRgDgWQgGgpAagnIAFgHQALAOASAIQAWAKAYgEQAfgEAdgdQAUgTAVglIACgDQAKAFAHAIIALANIAGAIQgEAUAFAVQAHAaASAQQATARAbACQAaADAVgOQAOgJAMgSQAIgKALgWQAegCAPACIAAAAQABgfASgWIAdgfIAPgOQAIAMAQAKQAQAKARACQAbAEAYgPQAXgPALgbQAFgKAFgXIABgFIAEAAQAKACAJADIAAAEQgDAcgFANIgJAWQgHANgCAIQgIAdAPAbQAPAcAcAKQAYAIAagHIgCADQgDAIgVAcQgRAXgFAFQgTASgfADQgaADgdgKIgSgGIgSgEIgegEQgPgDgPgGIgDAMQgIAWgRAOQgSAOgdAFQgQADgbAAIgKAAgABbB7QgUAAgJgCQgRgDgWgMQgkgVgSgYQAZgLAOgXQANgUAIgnQAHglAFglIABAAIAYgGQABAaAPAWQAVAdAiAEQAOABAMgDQAigIAQgaQAKgQAFggIAEgkQAOgNAVgNIAbgPQAEARANAQQATAVAaAFQAbAGAZgOQAXgMALgWQAKAOAQAKQAUAMAXAAIABAAQACALAFAIQALAUAVALQAWAKAWgCQAXgDASgPQASgPAHgWQADgHABgIIAEgBQAMgCAZAAQAfAAARAGQAXAIAPAWQAPAXgCAZIgEAbIgBAQIgCAQQgEAVgTAQQgPAPgYAIQgQAHgMABIgWABIgmAAIgXgBQgXgDgcgRIgQgKIgIAGQgTAPgZAGQgPAEgmABQgdAAgPgCQgcgCgugLIgkgJIgVgFIgJAMQgRAZgMANQgUAVgXAKQgRAIgSADQgKABgSAAg");
	this.shape_3.setTransform(-142.6242,-52.3964);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0099FF").s().p("AAoCqIgDgHIAKgJQAQgSAEgYQAEgZgKgWQgHgNgSgVQg3g9hEgxIgDgKQgEgVAHgVQAHgWAQgOQAQgOAWgEQAWgEATAIQAbAMASAdQgPADgOAIQgTALgKASQgJATABAWQABAVALASQAHAKAWASQAUASAHANQAEAGAHAWIAKAnIAJAgQgKAHgIALQgIAKgDAKIgGADIgLAIIgGgRg");
	this.shape_4.setTransform(-172.2227,-159.6417);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#0033CC").s().p("ADEIUQgJAAgJgCQgKgDgKgFQgSgKgKgRIAAgBQAEgGADgHQANglgUg0QgHgSgKgTQgJgVgIgMIgXgeIgNgUIgOgTQgNgOgRgIIgNgFQACgHAEgGQANgXAVgKQAPgHAPAAQAJAAAIABQAaAFARARIAVAbIASAWIAEAFIABABQAbAiAqBKQAVAkAGAXIAEASQAEAigSAbQgLAQgSAKQgRAJgTAAIgCAAgADRB1QgXgBgSgMQgNgIgRgTQgyg1g2gvIgDgDQgagXgJgMQgTgWgGgVQgGgXAIgYQAHgXASgPIABgBIgJgPIgRggQgNgWgkghQgYgZgRgLQgQgKgagJIgsgPQg2gTgTgiQgLgTACgXQABgXAMgSQANgSAVgJQAWgJAVAEQALABANAGIAWAJIA3ATIAGACQgMALgIAPQgKATACAVQACAVANASQAMASAUAJIAeAKQAJAEAUAPQA3ApAcAdIAeAiQATASASAIQAWAJAYgFQASgEANgKIADAIIAGAQQgMAKgHAOQgKATAAAgQAAAdAJAXQADAJALAVIAWAwQAPAbATAOIALAGIgFALQgLAVgTALQgSAKgVAAIgEAAg");
	this.shape_5.setTransform(-190.209,-122.0749);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006699").s().p("ACyIyQgWgCgTgOQgSgOgIgUQgGgOgCgCQgDgCgNgFQgRgGgOgOQgFgGgEgGQgGgJgDgKQgCgKAAgLQAAgIABgIQAEgTAMgPQANgQAVgIQAVgIAXADIAQAEQAbAIAbAVQAoAeAPAmQAJAVgBAWIAAAIQgCATgJAPQgMATgUALQgSAJgSAAIgHgBgAI/GtQgYgGgQgSQgHgIgJgQIgPgZQgHgKgVgVQgTgSgHgNQgOgcAHgdQAFgWAQgPIAMgKQAMgHANgDQATgFAWAGQATAGAUARQAVASAdAmQAWAbAIASQAOAbgBAYQgBAYgPAUQgLAPgPAIIgLAFIgKACQgHACgIAAQgKAAgLgDgAncGoQgIgDgJgEIgIgGQgPgKgJgQQgKgRgFgfQgHgpgDgKQgDgNgHgPIgHgNIgGgLIgQgcQgZgyAHgjQAEgXASgRQARgSAXgEQAUgEATAGIAHADQAXAKAMATQAFAHAFAMIAIATQAFANANAWIASAkQAIARAIAaQAGAYAHAfQAJAwgIAaIgBADQgHAUgSAOQgTAOgYACIgFAAQgLAAgLgDgAJ3BMIgLgDQgOgEgMgLQgRgOgHgUIgFgJIgLgKQgQgKgJgSQgJgSAAgTQABgSAIgQIACgDQAKgRAQgKQAVgMAdgBIAMAAQAdABAVAOQARALALARIANAcQAMAiACAQQAEAlgVAbQgNAQgVAIQgOAGgOAAIgOgCgApQioQgMgBgLgFQgNgGgSgQQgWgTgIgFIgQgKQgZgTgGggQgEgfASgaQARgZAhgHQAdgGAeAOQALAFAXASIAEADQAVARAKALQASATAGATQAHAWgGAXQgGAXgRAQQgJAHgKAFQgLAFgLABIgLABIgLgBgAFCjKQgTgCgRgLQgSgMgJgRIgPgbQgKgRgDgYIgBgTQABgRADgLQAFgOAHgLQAJgMAMgJQAPgMAUgDQATgDATAGQASAGAOAOQAOAPAFATIAHAhIAIAWQAGATgEAUQgDAVgNAPQgMAQgTAIIgLAEQgKADgMAAIgGAAgAnUkHQgYgQgIgZIgFgLQgEgGgKgDIgcgKIgEgCQgOgGgJgGQgSgMgKgVQgJgVADgWQADgWAQgRIAEgFQAOgOASgFQAYgHAgAHQASAFAiARQAlATAQAPIADABQASAQAMAVQAHAPAFARIAEAPQACASgDAOIgCAKQgHAUgRAPQgWATgaABIgFAAQgYAAgVgOgAHklIIgCgBQgTgEgPgNQgRgPgHgTIgGgUQgDgGgHgKQgNgSgHgRQgKgZADgVQAFgcAYgTQAVgPAXgCQAKgBAJABQAkAGAUAcIASAdIAOAVQAGAKAFAPQAKAcgDAWQgBAQgGANQgFAKgIAJQgNAQgVAHQgNAEgNAAIgPgBg");
	this.shape_6.setTransform(-148.487,-111.5736);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000066").s().p("AHLJWQgVgNgRghIgNgbIgHgNIgHgNIgDgEIgZgiQgKgNgGgMIgEgCQgZgKgOgWQgHgLgKgXIgQgZQgMgPgEgJIgMgaIgTggQgLgUgEgOQgFgVAGgWQAGgWAQgOIABgBIAGgFIADgCIgEgEIgHgMIgCgFIgEgNIgGgNIgNgVIgLgUQgGgJgNgHIgXgNIgDgCIABASQAAAXgEANQgFASgPAPQgOAOgTAGQgLAEgLAAQgIAAgIgCQgUgEgPgLQgHgGgFgGQgMgPgDgUIgDgYQgDgJgIgLIgPgTQgMgSAAgYIAAgMQgJgFgIgGQgOgMgIgSQgIgRACgTIADgYIgCgbIgBgKIgCgfIgJgrQgFgbAAgVQAAgeANgUQALgUAWgKQAVgKAXADQAVADASAPIAFAFQAJAIAFALQAEAGACAHIAEATIACASIADATIADAOIACAQIAEAcIADAiQAFAkgBAXQgBAOgDAMIANAJQAKAHAJAKQAMAMALAUQADgOAHgMQAEgIAGgGQAGgIAJgGQAPgKAUgCQATgDASAGQAOAFAYAPQAWAPAOAMIAMAMQAMANASAhIANAXIAFAJQAHgQANgKQAOgNATgEIALgCIAGgBQAbgBAaARIAJAGQgIAQgBARQAAATAJASQAJASAQALIALAKIAFAKQAHAUARAOQAMAKAOAFIADALQAEARgFASIgCAGQgIASgPAOQgQANgTAFQgUAEgUgFQgKgDgJgFQgIgFgHgGQgPgOgPgfQgLgVgKgbQgJgYgFgIIgHgKQgDAIgEAIQgJARgQAKIgBABQAKALAJAPIARAjQALAXAHALIAaApQgPAPgFAVQgHAeAOAbQAHANATATQAVAVAHAJIAPAZQAJAQAHAIQAQASAYAHQATAFARgEIgBAOQgEAcgSATQgTATgcADIgLABQgWAAgSgLgAhxHcQgZgEgSgTIgFgFQgOgRgEgVQgBgJABgPIgBgYQgCgWgLgUIgNgSIgHgMIgEgHQgIgRAAgTQABgTAKgQQAJgQAQgKIAIgFQAMgGAOgCIANgBQAMAAALAEQASAFAPANQALAJANAUIAFAJQATAfAJAjQAKAmAAAqQAAAigLAVIAAABQgMAWgWAMQgSAJgTAAIgMgBgAlqFlQgOgCgMgGQgSgIgLgNIgJAMQgHgagIgSIgSgjQgNgXgFgNIgIgTQgFgLgFgHQgMgUgXgJIgIgDIABAAIACgBQARgIARAAQAEgNAJgLQAOgSAXgIQAJgDAIgBQAOgCAOAEQAVAFAUASQAOAMATAXQApAzALAlQAHAagFAZIgBAGQgGAXgQAPIgCABQgJAJgMAFQgPAGgQAAIgHAAgAkQB9QgZgGgQgRQgMgNgMgaQgOgigFgIQgIgOgSgSIgBABQgSAUgZAFQgZAGgZgMQgRgHgMgNIgJgMIgHgOIgIgNQgNgRgjgMIgDAAQALgFAJgIQARgPAGgXQAGgXgHgWQgGgUgSgTQgKgLgVgQIAKAAIAFABIAcAKQAKAEAEAFIAFALQAIAZAYAQQAXAQAbgCQAagBAWgSQARgQAHgTIAKAGQAhAUAYAVIAkAiQAdAdAMAQQAVAcAVAwQAOAgABAVQAAAYgOAVQgKAPgOAJIgMAGQgNAGgPAAQgJAAgJgCgAFogvQgagOgKgdIgFgUIALgEQATgJAMgPQANgQADgUQAEgUgGgTIgIgWIgHgiQgFgSgOgPQgOgPgSgGQgTgGgTADQgUAEgPALQgMAJgJANQgHAKgFAPQgDALgBAQIABATIgLgBQgUgEgQgMQgLgJgHgLIgFgLQgIgTADgTQABgIAEgLIAGgSQAKgegBgWQAAgJgDgRIgDgZIABgWIgBgSIAAgEIgCgTIgCgUQgBgUALgTQAKgSARgLQARgLAVgBQAVgBASAIQATAJANAQQAIAMAFAOIADALQACAKAAANIgBAXQAAATADAkQADAmAAARIAAAVQASgEAUAEIAPAFQAHAQANASQAHAKADAHIAGATQAHAUARAOQAPAOATAEIACAFIAQAnQAEANADAZQAEAdgCAPQgEAZgRATQgMANgOAHQgHADgHACIgCAAQgJACgJAAQgTAAgSgKgAlikYQgVgFgQgNQgLgVgTgQIgDgFQgJgKgPgMQgUgQgWgLIgogUQgXgNgLgQQgOgSgBgXQgCgYAMgTIAEgHQAKgPASgIQAVgLAWACQAVACAfAOQA8AeAsAlQAhAbAXAfQAUAbAEAWIABAFQAEAZgOAYQgNAXgYAKQgPAGgQAAQgJAAgKgCgAjGmNQgSgBgRgJQgQgJgLgPQgIgNgEgDQgDgDgHgDIgLgFQgRgGgMgPIgIgLQgFgKgDgLQgEgSAFgSQAEgSAMgOQARgTAbgHQAZgGAaAGQAuAMAlAvIACACQATAZAFAXQAIAmgYAfQgGAHgHAGIgCABQgGAFgIAEQgPAHgRAAIgEAAg");
	this.shape_7.setTransform(-145.3695,-121.0275);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0099CC").s().p("AkPKdQgSgCgPgLQgPgLgJgQQgGgLgEgTIgGgfQgCgLgKgcIgDgLIgBAAQgRgygJgUQgPgjgZgrIABgDQAIgbgKgvQgGgfgHgYIAIgMQAMANARAIQANAGAOACQATABASgHQANgFAJgJQAKAVAYAqQAXApAKAWQAMAYANAiIAVA7IACAEIANAmQAHAZACATQAFA1gdAeQgNANgSAGQgMAEgNAAIgLgBgAh4JxQgWgIgPgVQgOgUAAgYQAAgKADgTQAEgUABgJQAAgPgEgTIgEgMIgGgWQgLgrAIgaIAEgLIAFAFQATATAZAEQAYAEAYgMQAXgMALgWQAKALAGARQAGANAFAYIACAKQAHAYACAPIAAAHQADAXgBAbQAAAfgFAWQgHAegQASQgQASgYAGQgKACgKAAQgOAAgNgFgAqYJcQgXgCgSgQQgSgPgHgWQgGgUACgXIAAgCIAIgtQAKgtAFgNQAHgXgBgIIgDgMIgDgMQgHgZALgaQAKgbAXgNQAYgNAbAEQAJACAHACIABABQAHAPAEAMQADAKAGApQAFAfAKASQAJAPAPALIAAACQgDAOgIAaQgIAbgDANIgGApQgDASgFANIgEAIQgMAUgVALQgRAIgRAAIgKgBgADbHbQAAgXgIgVQgPglgogfQgcgVgagIIgQgDIgEgKQgIggATgdQgKgMgEgPQgEgNAAgRIAAgfQAAgVgGgoQgHgpAAgVIgBgTIAAAAQALAAALgEQATgGAOgOQAOgOAFgSQAEgNAAgXIAAgSIADACIAWANQANAHAGAJIALAUIAOAVIAFAMIAFANIACAFIABAGIABARIgBABQgQAOgHAWQgGAWAGAVQADAOAMAUIATAgIALAaQAFAJALAPIAQAZQALAXAGALQAOAWAZAKIAEACQAHAMAKANIAZAiQgHAFgJAEIgHACQgQAFgRgBQgVgCgSgMQgKgGgHgIIAAATQAAAVgGARQgGARgOANQgKAKgLAFIABgHgAJuHAQgXgLgMgUIgBgBQAQgIALgPQAPgUABgYQAAgYgNgcQgJgRgVgbQgdgngWgSQgUgRgTgFQgVgHgUAFIACgNQAJAFALADQAUAFATgEQAUgFAPgNQAQgOAHgSIACgGIAJAFQAtAcAiA4QANAVAOAfIAXA1QANAdAEAPQAHAagEAUIAAABQgFAWgTASQgTARgXADIgKAAQgSAAgSgJgAkmDEIACgGQAEgZgHgaQgKglgqgzQgSgXgPgMQgUgRgVgFQgNgEgOACIglgiQgYgZgHgYQgEgLAAgLQAMAOASAHQAZAMAZgGQAZgFASgVIAAgBQASATAIAOQAGAIAOAiQALAaAMAMQAQARAZAGQAZAFAWgJIAMgGQAXAlAIAZIABAEIgIAFQgQAKgJAQQgJAQgBATQgBATAIARIAEAHIAAAAQgTAMgWAAIgCAAQgMAAgLgEgAhNB5QgMgUgMgJQgOgNgSgFQgMgEgLAAIgDgRIgBgbIgCghQgCgZgCgMIgLgkQgPgzACg2QAAgOACgMQgRAIgVgCQgcgCgTgRQgMgLgMgXIgVglQgHgKgVgWQgPgPgIgEQgHgDgNgEIgDgQQgFgQgIgPQAQANAVAFQAaAGAYgKQAXgKAOgXQANgYgDgZIgBgFIAFAEQArAgAhAtIAaAoQASAcAEAQQAEAOgBAPQASgKATAAIABAKIACAbIgEAYQgBATAHARQAIASAPAMQAIAGAJAFIgBAMQAAAYANATIAOATQAJALACAJIADAYQADAUANAOIABAGQABAZAAAMQAAAUgGAQQgJAWgUAOQgKAHgKADQgIADgJABIgFgJgAD/jDQgXgPgPgFQgSgGgTADQgTACgQAKQgIAGgHAIQgOgIgYgBIgXAAIgOgJQADgMABgOQABgXgEgkIgEgiIgDgcIASgCQAMgBAcACIAOABQAHALALAJQAPAMAUAEIALABQADAYALARIAPAbQAJASARALQARAMAUACQAOABAOgEQAAASgIARIgFAJQgOgMgXgPgAh/mjQgOgSgCgWIgDgaQgBgEgIgOIgCgFIgEgIQAIgGAFgHQAYgfgIgmQgFgXgTgZIAGgFQATgPAXgDQAXgCAWAMQAVALAMAVIAHASIACAFIAEANIASAvQAPAkgBAhIgFgFQgRgPgXgDQgWgDgWAKQgVAKgMAUQgMAUgBAeIgHgIgAm1m3QgRgOglgTQgigRgSgFQgggIgXAHQgTAGgOAOIgQgJQgbgPgKgJQgRgQgGgZQgFgZAJgWQAKgWAWgOQAVgNAYABQAQACASAGIAMAFIgEAHQgLATABAYQABAXAOASQAMAQAWANIApAUQAVALAUAQQAPAMAJAKIAEAFIgCgCgAFInPQgUgEgTAEIABgVQAAgRgEgmQgDgkABgTIAAgXQAAgNgCgKIgDgLQAOgEAPACQAVADAQAMQAJAGAQARIAbAfIAMAPQgYACgUAPQgZATgEAdQgEAVALAZIgPgFg");
	this.shape_8.setTransform(-143.9237,-110.8281);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#0066CC").s().p("AnKJjQgZgJgOgVIgGgJQgIgRAAgVQABgbAQgUIALgPQADgGgBgOQgCgQgEgOQAOAEAOgBQAXgCAUgOQASgOAHgUQAZArAPAjQAJAUASAyIgEALIgCAFQgKAUgUAUQgaAagWAHQgMADgLAAQgNAAgOgEgAipHkIgVg8QgNgigMgYQgKgWgXgpQgYgpgKgVIACgCQAPgPAGgWQAMADANAAQAWAAATgLIABgBIAHAMIANATQALATACAXIAAAXQAAAQABAIQADAVAPARIgFAMQgIAZALArIAHAWQgLAVgVAOIgCgEgAGYGfQgKgCgJgDIAHgDQAJgEAHgEIACADIAIANIgDAAIgLAAgAATGcIgDgJQgFgYgFgNQgGgRgKgMIABAAQAJgVAAgiQABgrgJgmIgCgZIgFgbIgFgRQAKgEAKgGQATgPAJgWQAGgPAAgUQABgNgCgYIAAgGQAFAGAGAFQAQAMAUAEQAIABAIAAIAAABIABATQAAAUAHApQAGApAAAUIAAAfQABASADAMQAEAPAKAMQgTAeAIAfIAEAKQgYgDgUAIQgWAIgMAQQgMAPgEATQgCAIAAAIIgGgDgAo8EAIgLgYIAGALIAHANIgCAAgAGrCeQgHgLgLgYIgRgjQgJgPgKgLIABAAQAQgLAJgRQAEgIACgHIAHAJQAGAJAJAXQAKAbALAVQAPAfAOAOQAHAGAJAFIgDAOQgMACgMAIIgNAKIgagogAjBATQAOgJAKgOQAOgWAAgYQgBgVgPggQgUgwgVgcQgNgRgcgdIgkgiQgYgVghgUIgLgGIADgKQADgOgDgSQANAEAHAEQAIAEAQAPQAVAWAGAJIAVAlQAMAXANALQASASAdACQAUABARgHQgCALAAAPQgCA1APAzIALAkQACAMACAZIACAhIACAcQgIAHgKAGQgKAGgKADQgJgagXgkgAoUAVQgCgLgBgWQgCgRgIgQQgFgMgIgHQgEgFgNgHQgPgLgKgRQgJgRAAgSQAAgQAGgPQALABAMgBQALgCAKgEIADABQAjALANASIAIANIAHANIAJAMQAAALADAMQAHAXAYAZIAlAiQgJABgJACQgWAIgPASQgIALgEANQgRAAgRAIQgOgQgEgVgAEGAnIAEAFIgDABIgBgGgAF+hRIgNgXQgTgigLgNIgMgLIAFgKQAIgRAAgSIAFAVQAKAcAZAOQAaAPAegGIACgBIANASIgMACQgSAFgPAMQgMALgHAQIgFgJgAH+hmQgagRgbABIgDgHIgDgQQAPgGALgNQASgUAEgYQACgPgFgdQgDgZgDgNIgQgnIgCgGIACABQAUAEAVgHQAUgHAOgQQAIgJAEgKIABABQAeAuAJAmQAFAVACAcIACAxQAAAcAAAOIgCALIgLAAQgdABgVAMQgQAKgLARIgBADIgJgGgAhskvQgEgPgRgcIgbgoQghgugrgfIgFgEQgEgXgVgbQgXgfgggbIAIgMIAIALQAMAPARAHIALAFQAGACAEAEQADADAJANQALAPAQAJQARAJASAAQASABARgIQAJgEAGgFIAFAHIADAFQAHAPABAEIADAaQADAVAOASIAHAIQgBAVAGAbIAJAsIACAfQgSgBgTAKQABgPgEgOgABRlwIgCgOIADgEQAQgXgIgTQgGgPgUgIQgFgKgJgJQABghgPgkIgTgvIgEgNQAHgGAJgDQAcgLAnAJQAVAGAoAVIADACIAAATIAAAVIADAaQADAQAAAJQABAWgKAeIgGASQgEALgBAIQgDAUAIATIAFAKIgOgBQgcgBgMAAIgSACIgDgQg");
	this.shape_9.setTransform(-147.45,-111.3516);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AqRDeQgtgFgigOQgdgNgOgTIgHgMIgIgLQgIgKgWgMQgZgTgJgiQgJghALghQATg6BDgjQAPgIAPgFIgBACQgCAXAGAUQAHAWASAPQASAQAXABQAWADAWgJQAVgLAMgUIAEgIIABAFQAGAWgIATIAVABQAHgVASgRIAFAJQAPAVAZAHQAZAJAZgIQAWgGAagaQAUgTAKgVIACgEIAIAAQAJAcACALIAGAfQAEASAGALQAJAQAPALQAPALASACQASADASgGQASgGANgNQAdgegFg0QgCgTgHgZIgNgmQAVgNALgVIADAMQAEATAAAPQgBAJgEAUQgDATAAAKQAAAYAOAUQAPAUAWAIQAWAIAZgFQAYgGAQgSQAQgRAHgeQAFgWAAgfQABgbgCgXIAIgEQAEAHAFAGQANAOASAGQANAEACADQACACAGANQAIAVATAOQASAOAWACQAWACAVgLQAVgLALgTQAKgPABgTQAMgFAJgKQAOgNAGgRQAGgRAAgVIAAgTQAIAIAJAGQASAMAVACQARABAQgFQAJAEAKABIAOABIAGANIANAbQASAhAUANQAXAOAcgEQAcgDATgTQATgTAEgcIABgOIAJgDIALgEIABABQAMAUAXALQAWAMAYgDQAXgDATgRQATgSAFgWIAGABQAfAJAUALQAWALAPAPQAQAOAIAOQAKASAFAbQAHAugMAiQgGATgOAPQgOAQgSAHQgTAIgogBIgtAAQgWAAgLgBQgPgCgPgGQgSAOgcAEQgPACgWAAIgmgBIgzgBQhegEhSgtIgSgMIgBACQgIAPgSASQgSATgKAIQgcAWghAGQgNADgQABQgoABgngNQgdgLgYgRIgJAOQgVAdggAOQgoARg9gGQgYgCgNgFIgOgHQgRAYgfAIQgNADgbAAIgYgBIgEARQgJAZgTANQgWAQgoAAIgggBIgggBIgqAFIgqACIgSAAQgqAAgWgCg");
	this.shape_10.setTransform(-143.2459,-50.4333);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6}]},2).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},2).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6}]},2).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},2).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6}]},2).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},2).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6}]},2).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},2).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6}]},2).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},2).wait(2));

	// river
	this.instance = new lib.CachedBmp_6();
	this.instance.setTransform(-219.95,-82.95,0.5,0.5);

	this.instance_1 = new lib.CachedBmp_7();
	this.instance_1.setTransform(-219.95,-82.95,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},21).wait(1));

	// leaves
	this.instance_2 = new lib.CachedBmp_8();
	this.instance_2.setTransform(-353.45,-182.45,0.5,0.5);

	this.instance_3 = new lib.CachedBmp_9();
	this.instance_3.setTransform(-353.45,-182.45,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2}]}).to({state:[{t:this.instance_3}]},21).wait(1));

	// trees
	this.instance_4 = new lib.CachedBmp_10();
	this.instance_4.setTransform(-366.45,-182.45,0.5,0.5);

	this.instance_5 = new lib.CachedBmp_11();
	this.instance_5.setTransform(-366.45,-182.45,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_4}]}).to({state:[{t:this.instance_5}]},21).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-366.4,-182.4,742.5,217.5);


(lib.mothmanflying = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// flyingCraneCrane
	this.instance = new lib.CachedBmp_4();
	this.instance.setTransform(-47.2,-39.45,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12));

	// flyingCraneBodyOutline
	this.instance_1 = new lib.CachedBmp_5();
	this.instance_1.setTransform(-51.3,-30.85,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(12));

	// flyingCraneRightWing
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAoDeIgCgBIgBAAIgBgBIgBAAIgBgBIgBgCIgBgBIAAAAIgNgDQgggHgQgDQgOgDgcgCQiAgHhAABIAAABIAAACIgBAAIAAACIgBABIAAABIgBABIgBABIgBABIgBAAIgCABIgBAAIgBAAIgCAAIgBAAIgBgBIgBAAIgBgBIgBgBIgBgBIgBgBIAAgBIgBgCIAAAAIAAgCIAAgEIgPAAIAAABQgBABAAAAQAAAAgBAAQAAABgBAAQgBAAAAAAIgBAAIgBABIAAAAIgBABIgBABIgBAAIgBAAIgBABIgBAAIgBAAIgBAAIgBAAIgBAAIgBAAIgBgBIgBAAIgBAAIAAgBIgBgBIgBAAIAAgBIgBgCIAAgBIgBgBIAAgBIAAgBIAAAAIAAgBIABgBIAAgBIABgCIAAgBIABAAIABgBIAAgBIABAAIABgBIABAAIABAAIABAAIABAAIABAAIABAAIABAAQABgLgDgQIgEgbQgBgSABgUIABhPIABgSIAIgbIAFgWQADgNAFgIQAFgJAPgMIAigfQAGgFADACQABAAAAAAQABABAAAAQAAABABAAQAAABAAAAIABgCIACgDIABgDIACgDIABgDIABgBIABgCIADgCIACgCIACgDIABgBIABgCIABgBIABgBIABgBIABgBIABgBIABgBIABgBIABgBIAAgBIABAAIAAgBIABgBIABgBIABgBIABgCIABgBIABgCIABgBIABgBIABgBIACgBIABgBIABgBIABgBIACgCIABgBIABgBIACgBIABAAIABgBIABgBIABgBIABgCIABgBIACgBIABgBIACgBIABAAIACAAIABgBIACgBIABAAIACgBIABgCIACAAIABgBIABgBIACgBIABgBIACAAIABgBIACAAIABgBIACAAIABgBIACAAIACAAIABgBIACgBIABAAIACgBIACAAIABgBIACAAIABAAIABAAIACAAIABAAIACAAIACgBIABAAIACgBIACAAIABAAIACAAIABAAIACAAIABAAIACAAIABAAIACAAIACAAIABgBIACAAIABAAIABgBIAEAAIAEAAIADAAIADAAIAEAAIACAAIACAAIACAAIABAAIAEAAIACAAIACAAIACAAIABAAIACABIACAAIACABIABAAIACAAIACABIACAAIACABIACAAIACAAIABABIABAAIABABIABABIACABIABABIACABIABAAIABABIABABIABAAIAAABIABAAIACABIABABIABACIABAAIABABIABABIABABIABACIABABIABACIABACIABABIABABIABACIABACIABABIAAACIABABIABABIAAABIABACIAAABIABACIAAACIABABIAAACIAAABIAAACIABACIAAABIABABIAAABIAAACIAAABIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAACIAAAAIABACIABABIABACIABABIABABIABABIABABIABABIACABIABAAIABABIABABIACABIABABIABABIACAAIAAABIABAAIABABIACAAIABABIABAAIACABIABABIAKAAIALAAIANAAIANAAIAMAAIANAAIALAAIAMAAIAJAAIAKgBIAJgBIAHAAIAGAAIAIAAIAFAAIAHAAIAGAAIAHAAIAGAAIAFAAIAGAAIAGABIACABIACAAIABAAIACAAIACAAIABAAIACABIABAAIABABIACAAIABABIABAAIADABIADABIAEABIADACIADABIADACIADACIADABIADABIADACIABAAIADACIACABIABABIACABIABABIABAAIAAABIABABIABABIABABIABABIABABIACABIABABIABABIABAAIABABIABABIABACIABABIABABIABABIABABIABABIABABIABABIABABIABACIABABIABACIABABIABABIABABIAAABIABABIAAABIABACIABABIABABIAAABIABABIAAABIABACIABACIABABIAAABIABACIABABIAAACIABACIAAACIABABIAAABIABACIAAACIABACIAAABIABACIAAABIAAACIABACIAAABIAAABIABACIAAACIAAACIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAACIAAAAIAAADIAAACIAAABIAAAEIAAABIgBACIAAABIAAABIgBABIAAABIgBABIAAABIgBACIgBABIgBACIgBABIAAABIgBABIgBABIAAACIgBACIgBABIgBABIgBACIgBABIgBACIgBABIAAACIgBABIgBABIgCABIgBABIgBACIgBABIgBABIgBABIgBACIgBABIgBACIgBACIgBABIgBABIgBABIgBABIgBABIgBABIgBACIgBABIgBACIgBAAIgBACIAAABIgBABIgBACIgCABIgBACIgHAFIgHAGIgHAGIgHAFIgHAGIgIAFIgIAEIgHAGIgHADIgHAEIgEADIgDACIgDACIgDADIgDACIgDABIgCACIgCABIgBABIgCADIgDABIgDACIgBABIgBABIgCAAIgBABIgCABIgBABIgCABIgCAAIgBABIgCABIgCABIgBABIgBABIgBABIgBABIgCABIgBABIgBABIgBAAIgBABIgCAAIgBABIgBABIgBABIgBAAIgBABIgCACIgBABIgBABIgCABIgBAAIgCABIAAAAIgBABIgBABIgBABIgCABIgBABIgBABIgBAAIgBABIgBABIgCAAIgBABIgBABIgCAAIgBABIgCAAIgBABIgCACIgBABIgBAAIgCABIgBAAIgBAAIgCABIgBAAIgBABIgCAAIgBABIgBAAIgCABIgBABIgCAAIgBABIgBABIgBABIgBAAIgCAAIgBABIgCAAIgCABIAAAAQADAEgFAEQgBABgIADIgQABIAAAAIgCACIgCAAIgBABIgBAAIAAAAIgCABIgBAAIgCABIgBAAg");
	this.shape.setTransform(5.725,-27.65);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(12));

	// flyingCraneLeftWing
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AhCC/IgBAAIgBAAIgCgBIgBAAIgBgBIgBgBIgBgBIAAgBIgBgBIAAgBIgBgBIAAgCIAAgOIAAgOIAAgOIAAgOIAAgOIAAgOIAAgOIAAgPIAAgQIAAgPIAAgQIAAgPIAAgOIAAgOIABgCIAAgBIAAgCIABgBIABgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgBIAAgCIAAgBIAAgCIAAgBIAAgCIABgBIAAgBIABgBIAAgBIAAgCIAAgBIAAgBIABgCIABgBIAAgCIAAgBIAAgBIAAgCIABgBIABgCIAAgBIABgBIAAgCIABgCIAAgBIABgBIAAgCIABgBIAAgBIAAgBIABgBIAAgBIABgBIAAgCIABAAIAAgCIABgCIABgBIABgCIABAAIAAgCIABgCIAAgBIABgBIABgBIABgBIABgBIAAgBIABgBIABgCIABgBIABgCIABgBIABgCIABgBIABgBIABgBIABgBIABgBIABgBIABgBIABgBIABgBIABgBIABgCIABgBIABgBIABgBIACgBIABgBIABAAIABgBIABgBIAAgBIABgBIABgBIABgBIABgBIACgBIABgBIABgBIABgBIABgBIABgBIABAAIABgBIABAAIABgBIABgBIABgBIABAAIABgBIABgBIABgBIABgBIABgBIABgBIABgBIAAgBIABAAIAAgBIABgBIABgBIABgBIACgBIABgBIACgBIABAAIABgBIAAgBIABgBIABgBIABgBIACgBIABAAIABgBIACAAIABgBIABgBIABAAIABgBIACgBIABAAIABgBIACgBIABgBIABgBIACAAIABgBIACAAIABgBIABgBIACgBIACAAIABgBIACAAIABgBIAAgBIABAAIABgBIACAAIABgBIABAAIACAAIABgBIACgBIABAAIACAAIABgBIABgBIACAAIABAAIABAAIACAAIABAAIABABIACABIABABIABABIAAABIABABIAAABIAAABIABACIAAABIgBABIAAACIgBABIAAABIgBABIgBABIgBABIgBAAIgCABIgCABIgBAAIgCAAIgBABIgBABIgCAAIgBAAIgBABIgBABIgCABIgBABIgBAAIgBAAIgCABIgCAAIgBABIgBAAIgBABIgCABIgBAAIgCABIAAAAIgBABIgBABIgBAAIgCABIgCABIgBABIgBAAIgBABIgCAAIgBABIgBABIgBABIgBABIgBABIgBABIgBABIgCAAIgBABIgBABIgBABIgBABIgBABIAAABIgBABIgBABIgCABIAAAAIgBAAIgBABIgBABIgBABIgBABIgCABIAAABIgBABIgBABIgBABIgBAAIgBABIgBAAIgBABIgBABIgBABIgCABIgBABIgBABIgBABIgBABIgBABIgBABIgBABIgBABIgBABIgCABIAAABIgBACIgBABIgBABIgCABIgBABIgBABIgBABIgBACIgBABIgBABIAAAAIgBAAIAAABIAAAAIgBABIAAABIgBAAIAAACIgBACIgBABIgBABIgBABIAAABIAAACIgBABIgBABIAAABIgBABIgCABIAAACIgBABIAAABIAAACIgBABIAAACIgBABIAAABIgBABIAAABIAAABIgBABIgBACIAAABIAAABIgBABIAAABIgBACIAAABIAAACIAAABIgBABIAAACIAAABIgBABIAAACIAAABIgBABIAAACIAAABIAAACIAAACIAAACIAAACIAAACIAAACIAAABIAAACIgBACIAAACIgBABIAAACIgBABIAAAAIAAAOIAAAMIAAAOIAAANIAAAOIAAAOIAAAOIAAAOIAAAQIAAAQIAAAQIAAAQIAAAPIAAAMIAAACIAAABIgBABIAAABIgBABIgBABIgBABIgBABIgBAAIgBABIgBAAIgCAAg");
	this.shape_1.setTransform(-18.475,-26.925);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(12));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-51.3,-49.8,89.3,83);


(lib.lefteye = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgDAJIgEgDIgCgEIAAgCIABgDIADgEIAFgCIADABIAEACIADAEIAAAEIgCAEIgDADIgEABIgEgBg");
	this.shape.setTransform(-0.15,-0.4583);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1.5,1,1).p("AAMAAQAAAFgDAEQgEADgFAAQgEAAgEgDQgDgEAAgFQAAgEADgEQAEgDAEAAQAFAAAEADQADAEAAAEg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#323232").s().p("ACdAaIAFgDIgCACIgDAEIgDABIADgEgAidgJQgEgDAAgFQAAgFAEgDQADgEAFAAQAFAAAEAEQADADAAAFQAAAFgDADQgEAEgFAAQgFAAgDgEg");
	this.shape_2.setTransform(14.975,1.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.lefteye, new cjs.Rectangle(-2.2,-2.2,33.4,7), null);


(lib.forest = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666600").s().p("A8gMqQizAAllgHQlMgHihgKQkSgRjXgpQhegSg6gYQhQghgtg3Qgwg8gXh2QgfiaAFjvIAFjGQADh2gChQIgEhkQgCg6ACgpIACgsQAAgYgGgSIgKgaQgHgQgBgLQgEgdAXgjQAPgWAUgKQAYgNASAMQAGAEAJAKQAJAMAFAEQAJAHAPAEIAbAGQAkAJAEAYQAagPAgALQAhALALAdQAagIAtAIQA6ALAPAAIAggBQATgCAMACQARADANAKQANAKACAQQASgMAXADQAXACAQAOQAJgQAbgEQAhgBAOgEQAMgDAUgKQAWgLAJgDQARgGARAEQATAFAGAPQAXgXAkADQAjADATAaQAVgdApABQAoABAUAeQAEgNAPgHQANgGARAAIAfACQARABAMgEQAIgDAMgIQAOgLAFgCQATgLAYAEQAXADAPAQQAVgTAgADQAgACARAXQAPgQAXgEQAYgDATAKIASALQAKAGAIABQAKABANgGIAXgMQAXgJAYAKQAYAJALAWQAYgPAPgHQAWgKATgCQAYgDAUAKQAWALAHAUQAjgjAjgFQAVgDATAIQAUAJAJARQAXgfAsACQAtADATAhQAPgFAWAIQAYAMAMAEQAKADAUAEQAVAEAKADQAQAFALAKQANALADAOQAegMA3AIQBCAJAXgDIAmgJQAYgGAPABIAbADQARADALgDQAIgBARgJQAQgIAKAAQAHgBARAEQAPADAJgBQAJgCALgIIASgNQANgJAYgFQAbgGANgEQAOgEASgIIAggPQAdgMA/gPIB0gcQBTgVAbAmQAagZAoAFQApAFATAfQAQgVAigBQAMAAAyAHQAYAEAygBIBYgCIAiABQATABAOAEIAaAJQAQAGAKACQAJABARgBIAZAAQAPABALAHQAMAIACAMQAXgIAZAGQAZAFASARIANANQAIAHAIABQAJABALgHIATgNQAXgMApAIQA1ALAPgCQAOgBAVgIIAjgNQAUgGARADQAVAEAKANQAXgXAigGQAjgFAdAPQApgSAsAAQAMAAAlAFIA4AGQAbADAQgDQAKgCASgGQATgGAJgBQAPgDAOADQAPAEAHAMQARgRAXgIQAXgIAYADIAUAEQALACAIgBQAMgCARgLQAVgNAHgDQAXgJAaAMQAZAMAIAXQAmgZAbgIQAngMAbAQQAQgZAhgEQAhgDAWAVQAdgWATgKQAdgNAaADQAHABASAGQAQAFAJAAQAIABAOgDIAXgEQAUgBAgAKQApANALABQAXAEAigFIA4gKQAggEAZAHQAfAIAPAVQAfgUAmAGQAmAFAYAcQAQgRAYgGQAYgGAWAHIAVAIQANAFAJAAQARAAAagWQAbgXARgBQANAAAWAMQAXAMAMAAQAMABAVgJQAVgJALAAQALAAARAHIAcAJQAOADAUgCIAjgDQAVAAAjAIQBpAYAGA5QATgIAlANQAoANASgFQAKgDAOgKIAXgPQAMgHATgCIAhgDQAVgDAngMQBNgYAtgTIAsgUQAcgNARgGQA5gVA5AAQAegBA7AHQBGAJAqAAQAUAAAYgDQAggDAOAEQAbAIAPAfQALAXAFAnQAcC8AKBgQARCdgBB/QgBArgPDoQgKCoAKBrQADAhAAAOQgBAagKASQgRAeg0AUQg/AYhWAGQgtADhugBQi1gCkEAJQrCAWrXA2IiaALQhVAFhEgBQg3AAhTgEIiJgIQhTgEijgDQjXgEhrACQktADn1AtQpXA3jMAKQjbALkNAAIgvgBg");
	this.shape.setTransform(373.7015,81.0535);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#666600").s().p("AgdBMQgWgJgOgVQgOgUAAgYQAAgXANgVQANgVAWgKQAQgIAOAAQAUAAAVAMQATAMALAVQAMAWgCAVQgCAXgOAUQgPATgVAIQgOAFgOAAQgOAAgPgGg");
	this.shape_1.setTransform(-826.0852,-458.713);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.forest, new cjs.Rectangle(-834.1,-466.9,1581.5,629), null);


(lib.foreground = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#003300").s().p("Ae8ITQg2grgPhBIgDgQQgBgMAAgMQABhMA0g2QAegfAlgPQAcgLAggCQAwgCAoATQANgaAVgWQA0g2BLgEQANgBAMABIAVADQAvAJAoAiQA6AzAGBNQAGBMgwA6IgJALQgvAyhHAHQg0AFgtgVQgKAUgPASQgxA7hNAIIgWABQg+AAg0gogEgqUAHqQgrgjgSgyQgHgTgDgVQgCgMAAgMQABhLA0g3QAyg0BIgGIAFAAIAFAAQgHgUgEgXIAAgFIgCgTQAChAAmgxIAOgQQA0g2BLgEQBLgEA6AyQAfAbAQAhQAOAdADAiIAAAEQACASgCASQAgAMAcAYQA6AzAGBNQAEAngMAiIgGAQQgKAYgSAVQgyA8hNAIQhLAIg8gvIgLgJQgJASgPARQgxA8hNAIIgWABQg+AAg0gogEAvwAGXQgQgNgOgQQghgogJg3QgBgMAAgMQABhMA0g2QAYgYAbgPQAGg0AfgpQgdgKgZgUQg9gwgLhNQgCgMAAgMQABgkAMgfQAOgiAbgdQA0g2BLgEQBLgEA6AyQAtAnAOA4QAggPAmgCQBLgEA6AyQA6AzAGBNQAGBLgwA6IgMAOQgvAvhEAHIgDAAQgGA2gkAsQgbAggiARQgEA5gnAuQgJAMgLAKQgsAng+AGIgWABQg+AAg0gogEgwBAFuQgXgTgQgWQgaglgHgvQgCgMAAgMQAChLA0g3QAegfAmgPQgegYgSgdQguAshDAHQgaADgYgEQAjAsAFA7QAGBMgxA6QgxA8hNAIQhFAHg5gnIgKgHQg8gwgLhNQgCgMAAgMQABhHAvg0QA2AjBCgHQBNgIAxg7QAxg6gGhMQgGhNg7gzQg5gyhMAEQhLAEg0A2IgMAOQgygugKhFQgCgMAAgMQABhLA0g3QA0g2BLgEQBMgEA5AyQA7AzAGBNQADAlgKAhQAYgIAbgCQBLgEA6AyQAZAXAQAbQAzgyBHgEQBMgEA5AyQAaAXAQAbQAUAjADArQAGBMgxA5QggAngtARIAHAGQA6AzAGBNQAGBMgwA6QgaAfghASQgfAPglAEIgVABQg/AAgzgogAcSDHQgXgKgUgQQg9gwgLhNIgCgYQACg2AbgrQALgRAOgPQAMgMANgKQAsghA6gDQBAgEAzAkIASAOQAeAaAQAhQAPAfADAlQAGBMgwA6QgMAPgOALQgqAkg7AGIgVABQgmAAghgOg");
	this.shape.setTransform(-0.042,19.6684);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#00CC00").s().p("EgwgAF1Qg9gwgLhNQgCgMAAgMIABgJQA4AnBFgIQBNgIAyg7QAwg7gGhMQgEg6gjgrQAYAEAagDQBDgHAuguQARAfAeAYQgmAOgeAgQg0A1gBBMQAAAMACAMQAHAvAZAkQAABBgrAzQgyA8hNAIIgVABQg/AAgzgogEArrAFHIAJgKQAxg7gGhMQgGhNg7gzQgngigwgJQA0g1BLgEQA5gDAuAbIACgPQgWgigHgsIAAgBQgCgMAAgMQAChMA0g2QA0g3BLgEQBLgEA6AyQASAQAMASQAeApAEA1QACAagEAYQAaAnAEAxQAGBLgxA7QgxA7hNAIQg+AHg0gfQgFA4glAtQgOARgQAMQgpAhg4AGIgVABQgRAAgRgDgEgn9AEhQAigRAZgfQAxg7gGhMQgGhNg7gyIgGgFQAsgRAhgnQAwg7gGhMQgDgqgTgjQA9AEAwAqQA6AyAHBLQgnAxgBBBIABASIgEAEIgKAMQAJAPAGARQhHAFgyA1Qg0A2gCBMQAAAMACAMQADAVAHATIgRABQgtAAgngVgA15DrQg9gwgLhNQgCgMAAgMQACg5AegsQAJgPANgNQA0g2BLgEQBLgEA6AyQA6AzAGBMQAGBMgwA6QgjAqgwARQgVAGgXADIgVABQg/AAgzgogA71D9IgUgEQALgjgDgnQgGhNg7gzQgbgYgggLQABgRgBgTIAAgDQALgTAQgRQAWgXAZgOQAkgTAsgDQBFgDA2ApIAKAIQA6AzAGBMQAGBMgwA7QgrA0hAAMIgUADIgVABQgNAAgMgBgAc2CYQg9gwgLhNQgCgMAAgMQAChKA0g3QA0g2BLgEQAtgDAmARQgcAsgBA3IABAYQAMBLA8AwQAVAQAWAKQgGALgJAKQgyA8hNAIIgVABQg/AAgzgogEAlhABiQggACgcALQgPgRgJgUQANgMAMgOQAxg6gGhMQgDglgQggQAvgnBAgEQBLgEA6AyQA6AzAGBNQACARgCAQQgMgBgNAAQhLAEg0A3QgVAWgMAZQgpgTgvADgEgyNgBAIgPgLQg9gwgLhMQgCgMAAgMQAChCAogyIAMgOQA0g3BLgEQBLgEA6AyQA6AzAGBNQAGBMgwA7QgyA7hNAIIgVABQg2AAgtgdg");
	this.shape_1.setTransform(-31.392,29.3184);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006600").s().p("AMMFBQg8gwgMhMQgBgMAAgMQABhMA0g2QA0g2BLgEQAcgBAZAFQgOgTgIgVQgLggAAghQAAgZAGgYQAHgXAMgVQAMgVAQgRQARgRAUgNQAUgNAXgHQAXgIAYgBIAGAAIAEgBIAEAAQAqAAAmARQAjARAZAcQARASALAVIANgIQgNAKgMANQgOAPgLAQQgmgQgtACQhLAEg0A3Qg0A2gBBLQAAAMABAMQAMBMA8AwQA8AvBMgIQBNgIAxg7QAJgLAHgLQArATAxgFQA6gGArgkQAKAUAOARQglAOgeAgQg0A2gBBMQAAAMABAMIADAQQgogrgKg8QgvAyhGAHQhMAIg8gvQgVgRgQgVQgJArgeAkQgxA7hNAIIgWABQg+AAg0gogEgj9AFBQgUgQgPgTQgXAJgbADQhKAHg7gsQBAgNArg0QAxg6gGhMQgGhMg7gzIgKgJQAOgDAPAAQBMgEA5AyQAQANAMAQIAHgDQgeAsgBA6QAAAMACAMQALBMA8AwQA8AvBMgIQAXgCAUgHIgNASQgyA7hNAIIgVABQg/AAgzgogEAr4AE6QAKgKAKgLQAngvAEg4QAigSAbgfQAkgsAGg2IADAAQBEgHAvguQgDAggOAeQAgArAFA4QAGBMgxA7QgxA7hNAIIgWABQg+AAgzgogEAhvAE6IgPgNQAQgNANgQQAmguAFg3QAzAeA+gGQBNgIAyg8QAwg6gGhLQgEgygZgnQAEgYgCgZQgEg2gegpQANgiAbgcQAUgVAWgNQgMAfgBAkQAAAMACAMQALBNA9AwQAZAUAdAKQggApgFA0QgcAOgXAZQg0A2gBBMQAAAMABAMQAJA3AhAoQg2ACgvgbIgOATQgxA7hNAIIgWABQg+AAg0gogEgotAEDIAUAEQgMAHgOAEIAGgPgEgwnAAjIAKgLIAEgFIAAAFQAEAWAHAUIgFABIgFAAQgGgRgJgPgAdPATQABgQgBgQQgGhNg7gzQg5gyhMAEQg/ADgvAoQgQghgegaIgSgOQAMgvAjglQA0g3BLgEQBMgEA5AyQA7AzAGBNIAAAKQAbgKAegBQBMgEA5AyQAUARAOAUQAGArAXAiIgCAQQgvgcg5ADQhLAEgzA1IgVgCgEgqygBQQAZgJAdgCQATgBATADQgaANgWAXQgQARgLATQgDgigOgdg");
	this.shape_2.setTransform(48.9705,28.2934);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.foreground, new cjs.Rectangle(-363.7,-37.5,727.4,114.3), null);


(lib.flatwoodeyeyellow1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFF00").ss(1,1,1).p("AKZFdIAzkKQAyh9BohnQBuhuCHgzQB0gsCGAAQEiAADNDNQBnBnAzB9IAzEKEggQAFfIA0kKQAyh8BnhoQBuhuCHgzQB0gsCGAAQEiAADNDNQBoBoAyB8IAzEK");
	this.shape.setTransform(0.025,-35.275);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFF00").s().p("A5OKSQiHg0huhuQhnhngyh9Ig0kLIAAgEIA0kKQA0h6BlhmQBuhuCHgzQB0gsCGAAQEiAADNDNQBmBmA0B6IAzEKIAAAEIgzELQgyB9hoBnQjNDNkiAAQiGAAh0grgARbKPQiHgzhuhuQhohogyh9IgzkJIAAgFIAzkKQA0h7BmhlQBuhuCHgzQB0gsCGAAQEiAADNDNQBlBlA1B7IAzEKIAAAFIgzEJQgzB9hnBoQjNDNkiAAQiGAAh0gsg");
	this.shape_1.setTransform(0.025,0.225);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.flatwoodeyeyellow1, new cjs.Rectangle(-207.4,-71.4,414.9,141.8), null);


(lib.flattwoodanimation = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// flatwoodsoutline
	this.instance = new lib.CachedBmp_3();
	this.instance.setTransform(-48.55,-100,0.3177,0.3177);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.flattwoodanimation, new cjs.Rectangle(-48.5,-100,57.8,82.3), null);


(lib.clouds = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_2();
	this.instance.setTransform(-137,-67,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.clouds, new cjs.Rectangle(-137,-67,763,159), null);


(lib.Background_Sky = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Sky
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#97E8FF","#0075FF"],[0,1],-0.1,105.7,-0.1,-106).s().p("Eg2rAPoIAA/PMBtXAAAIAAfPg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Background_Sky, new cjs.Rectangle(-350,-100,700,200), null);


(lib.flatwoodsreye = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Eye
	this.flatwoodeyeyellow1 = new lib.flatwoodeyeyellow1();
	this.flatwoodeyeyellow1.name = "flatwoodeyeyellow1";
	this.flatwoodeyeyellow1.setTransform(129.5,-104.15,1,1,0,0,0,0,-0.3);

	this.timeline.addTween(cjs.Tween.get(this.flatwoodeyeyellow1).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.flatwoodsreye, new cjs.Rectangle(-77.4,-174.7,413.9,141.2), null);


(lib.bigfootanimation = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// eyes
	this.lefteye = new lib.lefteye();
	this.lefteye.name = "lefteye";
	this.lefteye.setTransform(10.25,-67.9);

	this.righteye = new lib.righteye();
	this.righteye.name = "righteye";
	this.righteye.setTransform(2.75,-64.85);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAAAGIgBAAIABAAIABgBIABgBIAAgBIABgBQAAgBAAgBQAAAAAAAAQgBAAAAAAQAAgBgBAAIgBgCIgCAAIgBABIgBABIAAgCIABgBIABgBIABAAIABgBIAAAAIADACIABABIABADIgBAAIABAAIAAACIAAABIgCACQAAABAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape.setTransform(10.4,-67.75);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.righteye},{t:this.lefteye}]}).wait(1));

	// white
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1.5,1,1).p("ABMgPQAAAKgLAGQgLAIgPAAQgPAAgLgIQgKgGAAgKQAAgKAKgHQALgHAPAAQAPAAALAHQALAHAAAKgAgBAQQAAAKgLAHQgKAHgQAAQgPAAgLgHQgLgHAAgKQAAgKALgHQALgHAPAAQAQAAAKAHQALAHAAAKg");
	this.shape_1.setTransform(6.875,-65.725);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhAAhQgLgHAAgKQAAgKALgHQALgHAPAAQAQAAAKAHQALAHAAAKQAAAKgLAHQgKAHgQAAQgPAAgLgHgAANABQgKgGAAgKQAAgKAKgHQALgHAPAAQAPAAALAHQALAHAAAKQAAAKgLAGQgLAIgPAAQgPAAgLgIg");
	this.shape_2.setTransform(6.875,-65.725);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).wait(1));

	// body
	this.instance = new lib.CachedBmp_1();
	this.instance.setTransform(-48.25,-80.35,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.bigfootanimation, new cjs.Rectangle(-48.2,-129,404.09999999999997,140.2), null);


// stage content:
(lib.cryptids33 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [98,156];
	// timeline functions:
	this.frame_98 = function() {
		var root = this;
		
		var bigfootanimationRestX = this.bigfootanimation.x;
		var bigfootanimationRestY = this.bigfootanimation.y;
		
		this.bigfootanimation.on("click", function(e) {
		      console.log("first click");
		      createjs.Tween.get(root.bigfootanimation, {override:false}).to({x: bigfootanimationRestX+10, y: bigfootanimationRestY+40}, 600, createjs.Ease.quintOut).call(emerge);
		});
		
		function emerge() {
		      console.log("will emerge")
		      createjs.Tween.get(root.bigfootanimation, {override:false}).to({x: bigfootanimationRestX, y: bigfootanimationRestY}, 2200, createjs.Ease.quintIn);
		};
		
		
		var mothmanflyingX = this.mothmanflying.x;
		createjs.Tween.get(root.mothmanflying, {override:false}).to({x: mothmanflyingX-1000}, 6000, createjs.Ease.quintOut).call(loopMothmanFlying);
		
		function loopMothmanFlying(){
		root.mothmanflying.x = 780; // starting position off stage right
		createjs.Tween.get(root.mothmanflying, {override:false}).to({x: mothmanflyingX-1000}, 6000, createjs.Ease.quintOut).call(loopMothmanFlying);
		}
		
		this.flattwoodanimation.addEventListener("click", link.bind(this));
		
		function link(e){
			var url = "https://www.mattgyver.com/tutorials/2022/10/1/cryptids-of-north-america";
			var win = window.open(url, "_blank");
			win.focus();
		}
		
		var root = this;
		
		this.stage.on("stagemousemove", function(e) {
		    var l2gL = root.bigfootanimation.lefteye.localToGlobal(0, 0);
		    var calcL = Math.atan2(e.stageY - l2gL.y, e.stageX - l2gL.x);
		    var angleL = calcL * (180 / Math.PI);
		    root.bigfootanimation.lefteye.rotation = angleL;
		
		    var l2gR = root.bigfootanimation.righteye.localToGlobal(0, 0);
		    var calcR = Math.atan2(e.stageY - l2gR.y, e.stageX - l2gR.x);
		    var angleR = calcR * (180 / Math.PI);
		    root.bigfootanimation.righteye.rotation = angleR;
		
		});
	}
	this.frame_156 = function() {
		this.stop()
		
		//this.gotoAndPlay(99);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(98).call(this.frame_98).wait(58).call(this.frame_156).wait(1));

	// Title
	this.instance = new lib.Title();
	this.instance.setTransform(234.9,68);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(28).to({_off:false},0).wait(1).to({regY:-1.2,y:63.1,alpha:0.0833},0).wait(1).to({y:59.4,alpha:0.1667},0).wait(1).to({y:55.7,alpha:0.25},0).wait(1).to({y:52.05,alpha:0.3333},0).wait(1).to({y:48.35,alpha:0.4167},0).wait(1).to({y:44.65,alpha:0.5},0).wait(1).to({y:40.95,alpha:0.5833},0).wait(1).to({y:37.3,alpha:0.6667},0).wait(1).to({y:33.6,alpha:0.75},0).wait(1).to({y:29.9,alpha:0.8333},0).wait(1).to({y:26.2,alpha:0.9167},0).wait(1).to({y:22.55,alpha:1},0).wait(1).to({x:236.45},0).wait(1).to({x:238.05},0).wait(1).to({x:239.65,y:22.6},0).wait(1).to({x:241.2},0).wait(1).to({x:242.8},0).wait(1).to({x:244.4,y:22.65},0).wait(1).to({x:246},0).wait(1).to({x:247.55},0).wait(1).to({x:249.15,y:22.7},0).wait(1).to({x:250.75},0).wait(1).to({x:252.35},0).wait(1).to({x:253.9,y:22.75},0).wait(1).to({x:255.5},0).wait(1).to({x:257.1},0).wait(1).to({x:258.7,y:22.8},0).wait(1).to({x:260.25},0).wait(1).to({x:261.85},0).wait(1).to({x:263.45,y:22.85},0).wait(1).to({x:265.05},0).wait(1).to({x:266.6},0).wait(1).to({x:268.2,y:22.9},0).wait(1).to({x:269.8},0).wait(1).to({x:271.4},0).wait(1).to({x:272.95,y:22.95},0).wait(1).to({x:274.55},0).wait(1).to({x:276.15},0).wait(1).to({x:277.75,y:23},0).wait(1).to({x:279.3},0).wait(1).to({x:280.9,y:23.05},0).wait(1).to({x:282.5},0).wait(1).to({x:284.05},0).wait(1).to({x:285.65,y:23.1},0).wait(1).to({x:287.25},0).wait(1).to({x:288.85},0).wait(1).to({x:290.4,y:23.15},0).wait(1).to({x:292},0).wait(1).to({x:293.6},0).wait(1).to({x:295.2,y:23.2},0).wait(1).to({x:296.75},0).wait(1).to({x:298.35},0).wait(1).to({x:299.95,y:23.25},0).wait(1).to({x:301.55},0).wait(1).to({x:303.1},0).wait(1).to({x:304.7,y:23.3},0).wait(1).to({x:306.3},0).wait(1).to({x:307.9},0).wait(1).to({x:309.45,y:23.35},0).wait(1).to({x:311.05},0).wait(1).to({x:312.65},0).wait(1).to({x:314.25,y:23.4},0).wait(1).to({x:315.8},0).wait(1).to({x:317.4},0).wait(1).to({x:319,y:23.45},0).wait(1).to({x:320.6},0).wait(1).to({x:322.15},0).wait(1).to({x:323.75,y:23.5},0).wait(1).to({x:325.35},0).wait(1).to({x:326.95,y:23.55},0).wait(1).to({x:328.5},0).wait(1).to({x:330.1},0).wait(1).to({x:331.7,y:23.6},0).wait(1).to({x:333.25},0).wait(1).to({x:334.85},0).wait(1).to({x:336.45,y:23.65},0).wait(1).to({x:338.05},0).wait(1).to({x:339.6},0).wait(1).to({x:341.2,y:23.7},0).wait(1).to({x:342.8},0).wait(1).to({x:344.4},0).wait(1).to({x:345.95,y:23.75},0).wait(1).to({x:347.55},0).wait(1).to({x:349.15},0).wait(1).to({x:350.75,y:23.8},0).wait(1).to({x:352.3},0).wait(1).to({x:353.9},0).wait(1).to({x:355.5,y:23.85},0).wait(1).to({x:357.1},0).wait(1).to({x:358.65},0).wait(1).to({x:360.25,y:23.9},0).wait(1).to({x:361.85},0).wait(1).to({x:363.45},0).wait(1).to({x:365,y:23.95},0).wait(1).to({x:366.6},0).wait(1).to({x:368.2},0).wait(1).to({x:369.8,y:24},0).wait(1).to({x:371.35},0).wait(1).to({x:372.95,y:24.05},0).wait(1).to({x:374.55},0).wait(1).to({x:376.1},0).wait(1).to({x:377.7,y:24.1},0).wait(1).to({x:379.3},0).wait(1).to({x:380.9},0).wait(1).to({x:382.45,y:24.15},0).wait(1).to({x:384.05},0).wait(1).to({x:385.65},0).wait(1).to({x:387.25,y:24.2},0).wait(1).to({x:388.8},0).wait(1).to({x:390.4},0).wait(1).to({x:392,y:24.25},0).wait(1).to({x:393.6},0).wait(1).to({x:395.15},0).wait(1).to({x:396.75,y:24.3},0).wait(1).to({x:398.35},0).wait(1).to({x:399.95},0).wait(1).to({x:401.5,y:24.35},0).wait(1).to({x:403.1},0).wait(1).to({x:404.7},0).wait(1).to({x:406.3,y:24.4},0).wait(1).to({x:407.85},0).wait(1).to({x:409.45},0).wait(1).to({x:411.05,y:24.45},0).wait(1).to({x:412.65},0).wait(1).to({x:414.2},0).wait(1).to({x:415.8,y:24.5},0).wait(1).to({x:417.4},0).wait(1).to({x:419,y:24.55},0).wait(1));

	// Foreground
	this.instance_1 = new lib.foreground();
	this.instance_1.setTransform(348.1,162.35);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({regY:19.7,y:181.55},0).wait(1).to({y:181.05},0).wait(1).to({y:180.6},0).wait(1).to({y:180.1},0).wait(1).to({y:179.6},0).wait(1).to({y:179.15},0).wait(1).to({y:178.65},0).wait(1).to({y:178.2},0).wait(1).to({y:177.7},0).wait(1).to({y:177.2},0).wait(1).to({y:176.75},0).wait(1).to({y:176.25},0).wait(1).to({y:175.75},0).wait(1).to({y:175.3},0).wait(1).to({y:174.8},0).wait(1).to({y:174.35},0).wait(1).to({y:173.85},0).wait(1).to({y:173.35},0).wait(1).to({y:172.9},0).wait(1).to({y:172.4},0).wait(1).to({y:171.9},0).wait(1).to({y:171.45},0).wait(1).to({y:170.95},0).wait(1).to({y:170.5},0).wait(1).to({x:348.05},0).wait(1).to({x:348},0).wait(1).to({x:347.95},0).wait(1).to({x:347.9,y:170.55},0).wait(1).to({x:347.85},0).wait(1).to({x:347.8},0).wait(1).to({x:347.75,y:170.6},0).wait(1).to({x:347.7},0).wait(1).to({x:347.65},0).wait(1).to({x:347.6,y:170.65},0).wait(2).to({x:347.55},0).wait(1).to({x:347.5},0).wait(1).to({x:347.45,y:170.7},0).wait(1).to({x:347.4},0).wait(1).to({x:347.35},0).wait(1).to({x:347.3,y:170.75},0).wait(1).to({x:347.25},0).wait(1).to({x:347.2},0).wait(1).to({x:347.15,y:170.8},0).wait(1).to({x:347.1},0).wait(2).to({x:347.05},0).wait(1).to({x:347,y:170.85},0).wait(1).to({x:346.95},0).wait(1).to({x:346.9},0).wait(1).to({x:346.85,y:170.9},0).wait(1).to({x:346.8},0).wait(1).to({x:346.75},0).wait(1).to({x:346.7,y:170.95},0).wait(1).to({x:346.65},0).wait(1).to({x:346.6},0).wait(1).to({y:171},0).wait(1).to({x:346.55},0).wait(1).to({x:346.5},0).wait(1).to({x:346.45},0).wait(1).to({x:346.4,y:171.05},0).wait(1).to({x:346.35},0).wait(1).to({x:346.3},0).wait(1).to({x:346.25,y:171.1},0).wait(1).to({x:346.2},0).wait(1).to({x:346.15},0).wait(1).to({x:346.1,y:171.15},0).wait(2).to({x:346.05},0).wait(1).to({x:346},0).wait(1).to({x:345.95,y:171.2},0).wait(1).to({x:345.9},0).wait(1).to({x:345.85},0).wait(1).to({x:345.8,y:171.25},0).wait(1).to({x:345.75},0).wait(1).to({x:345.7},0).wait(1).to({x:345.65,y:171.3},0).wait(1).to({x:345.6},0).wait(2).to({x:345.55},0).wait(1).to({x:345.5,y:171.35},0).wait(1).to({x:345.45},0).wait(1).to({x:345.4},0).wait(1).to({x:345.35,y:171.4},0).wait(1).to({x:345.3},0).wait(1).to({x:345.25},0).wait(1).to({x:345.2,y:171.45},0).wait(1).to({x:345.15},0).wait(1).to({x:345.1},0).wait(1).to({y:171.5},0).wait(1).to({x:345.05},0).wait(1).to({x:345},0).wait(1).to({x:344.95},0).wait(1).to({x:344.9,y:171.55},0).wait(1).to({x:344.85},0).wait(1).to({x:344.8},0).wait(1).to({x:344.75,y:171.6},0).wait(1).to({x:344.7},0).wait(1).to({x:344.65},0).wait(1).to({x:344.6,y:171.65},0).wait(2).to({x:344.55},0).wait(1).to({x:344.5},0).wait(1).to({x:344.45,y:171.7},0).wait(1).to({x:344.4},0).wait(1).to({x:344.35},0).wait(1).to({x:344.3,y:171.75},0).wait(1).to({x:344.25},0).wait(1).to({x:344.2},0).wait(1).to({x:344.15,y:171.8},0).wait(1).to({x:344.1},0).wait(2).to({x:344.05},0).wait(1).to({x:344,y:171.85},0).wait(1).to({x:343.95},0).wait(1).to({x:343.9},0).wait(1).to({x:343.85,y:171.9},0).wait(1).to({x:343.8},0).wait(1).to({x:343.75},0).wait(1).to({x:343.7,y:171.95},0).wait(1).to({x:343.65},0).wait(1).to({x:343.6},0).wait(1).to({y:172},0).wait(1).to({x:343.55},0).wait(1).to({x:343.5},0).wait(1).to({x:343.45},0).wait(1).to({x:343.4,y:172.05},0).wait(1).to({x:343.35},0).wait(1).to({x:343.3},0).wait(1).to({x:343.25,y:172.1},0).wait(1).to({x:343.2},0).wait(1).to({x:343.15},0).wait(1).to({x:343.1,y:172.15},0).wait(2).to({x:343.05},0).wait(1).to({x:343},0).wait(1).to({x:342.95,y:172.2},0).wait(1).to({x:342.9},0).wait(1).to({x:342.85},0).wait(1).to({x:342.8,y:172.25},0).wait(1).to({x:342.75},0).wait(1).to({x:342.7},0).wait(1).to({x:342.65,y:172.3},0).wait(1).to({x:342.6},0).wait(2).to({x:342.55},0).wait(1).to({x:342.5,y:172.35},0).wait(1).to({x:342.45},0).wait(1).to({x:342.4},0).wait(1).to({x:342.35,y:172.4},0).wait(1).to({x:342.3},0).wait(1).to({x:342.25},0).wait(1).to({x:342.2,y:172.45},0).wait(1).to({x:342.15},0).wait(1).to({x:342.1},0).wait(1).to({y:172.5},0).wait(1));

	// eyes
	this.instance_2 = new lib.flatwoodsreye();
	this.instance_2.setTransform(332.35,121.65,0.0526,0.0992,0,0,0,129.4,-103.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(157));

	// bigfooot
	this.bigfootanimation = new lib.bigfootanimation();
	this.bigfootanimation.name = "bigfootanimation";
	this.bigfootanimation.setTransform(509.5,270.25);

	this.timeline.addTween(cjs.Tween.get(this.bigfootanimation).wait(1).to({regX:153.8,regY:-58.9,x:663.3,y:211.35},0).wait(69).to({y:205.65},0).wait(1).to({y:200},0).wait(1).to({y:194.35},0).wait(1).to({y:188.7},0).wait(1).to({y:183.05},0).wait(1).to({y:177.4},0).wait(1).to({y:171.7},0).wait(1).to({y:166.05},0).wait(1).to({y:160.4},0).wait(1).to({y:154.75},0).wait(1).to({y:149.1},0).wait(1).to({y:143.45},0).wait(1).to({y:137.75},0).wait(1).to({y:132.1},0).wait(1).to({y:126.45},0).wait(1).to({y:120.8},0).wait(1).to({y:115.15},0).wait(1).to({y:109.5},0).wait(1).to({x:663.35,y:108.7},0).wait(1).to({x:663.45,y:107.9},0).wait(1).to({x:663.55,y:107.1},0).wait(1).to({x:663.65,y:106.3},0).wait(1).to({x:663.75,y:105.5},0).wait(1).to({x:663.8,y:104.7},0).wait(1).to({x:663.9,y:103.9},0).wait(1).to({x:664,y:103.1},0).wait(1).to({x:664.1,y:102.3},0).wait(1).to({x:664.2,y:101.5},0).wait(1).to({x:664.3,y:100.7},0).wait(1).to({x:664.25,y:100.9},0).wait(1).to({y:101.05},0).wait(1).to({x:664.2,y:101.25},0).wait(1).to({y:101.45},0).wait(1).to({y:101.6},0).wait(1).to({x:664.15,y:101.8},0).wait(1).to({y:102},0).wait(1).to({y:102.2},0).wait(1).to({x:664.1,y:102.35},0).wait(1).to({y:102.55},0).wait(1).to({y:102.75},0).wait(1).to({x:664.05,y:102.9},0).wait(1).to({y:103.1},0).wait(1).to({y:103.3},0).wait(1).to({x:664,y:103.5},0).wait(1).to({y:103.65},0).wait(1).to({y:103.85},0).wait(1).to({x:663.95,y:104.05},0).wait(1).to({y:104.25},0).wait(1).to({y:104.4},0).wait(1).to({x:663.9,y:104.6},0).wait(1).to({y:104.8},0).wait(1).to({y:104.95},0).wait(1).to({x:663.85,y:105.15},0).wait(1).to({y:105.35},0).wait(1).to({y:105.55},0).wait(1).to({x:663.8,y:105.7},0).wait(1).to({y:105.9},0).wait(1).to({y:106.1},0).wait(1).to({x:663.75,y:106.25},0).wait(1).to({y:106.45},0).wait(1).to({x:663.7,y:106.65},0).wait(1).to({y:106.85},0).wait(1).to({y:107},0).wait(1).to({x:663.65,y:107.2},0).wait(1).to({y:107.4},0).wait(1).to({y:107.55},0).wait(1).to({x:663.6,y:107.75},0).wait(1).to({y:107.95},0).wait(1).to({y:108.15},0).wait(1).to({x:663.55,y:108.3},0).wait(1).to({y:108.5},0).wait(1).to({y:108.7},0).wait(1).to({x:663.5,y:108.85},0).wait(1).to({y:109.05},0).wait(1).to({y:109.25},0).wait(1).to({x:663.45,y:109.45},0).wait(1).to({y:109.6},0).wait(1).to({y:109.8},0).wait(1).to({x:663.4,y:110},0).wait(1).to({y:110.15},0).wait(1).to({y:110.35},0).wait(1).to({x:663.35,y:110.55},0).wait(1).to({y:110.75},0).wait(1).to({y:110.9},0).wait(1).to({x:663.3,y:111.1},0).wait(1).to({y:111.3},0).wait(1).to({y:111.5},0).wait(1));

	// flattwoodsmonster
	this.flattwoodanimation = new lib.flattwoodanimation();
	this.flattwoodanimation.name = "flattwoodanimation";
	this.flattwoodanimation.setTransform(370.65,316.15,1.5738,1.4026,0,0,0,0.3,65.1);

	this.timeline.addTween(cjs.Tween.get(this.flattwoodanimation).wait(157));

	// mothman
	this.mothmananimation = new lib.mothmanflying();
	this.mothmananimation.name = "mothmananimation";
	this.mothmananimation.setTransform(755.9,39.4);

	this.mothmanflying = new lib.mothmanflying();
	this.mothmanflying.name = "mothmanflying";
	this.mothmanflying.setTransform(759.7,39.4);
	this.mothmanflying._off = true;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.mothmananimation}]}).to({state:[{t:this.mothmanflying}]},98).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).to({state:[{t:this.mothmanflying}]},1).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.mothmanflying).wait(98).to({_off:false},0).wait(1).to({regX:-6.7,regY:-8.3,x:735.75,y:31.1},0).wait(1).to({x:718.5},0).wait(1).to({x:701.25},0).wait(1).to({x:684},0).wait(1).to({x:666.75},0).wait(1).to({x:649.5},0).wait(1).to({x:632.25},0).wait(1).to({x:615},0).wait(1).to({x:597.75},0).wait(1).to({x:580.55},0).wait(1).to({x:563.3},0).wait(1).to({x:546.05},0).wait(1).to({x:528.8},0).wait(1).to({x:511.55},0).wait(1).to({x:494.3},0).wait(1).to({x:477.05},0).wait(1).to({x:459.8},0).wait(1).to({x:442.55},0).wait(1).to({x:425.3},0).wait(1).to({x:408.1},0).wait(1).to({x:390.85},0).wait(1).to({x:373.6},0).wait(1).to({x:356.35},0).wait(1).to({x:339.1},0).wait(1).to({x:321.85},0).wait(1).to({x:304.6},0).wait(1).to({x:287.35},0).wait(1).to({x:270.1},0).wait(1).to({x:252.9},0).wait(1).to({x:235.65},0).wait(1).to({x:218.4},0).wait(1).to({x:201.15},0).wait(1).to({x:183.9},0).wait(1).to({x:166.65},0).wait(1).to({x:149.4},0).wait(1).to({x:132.15},0).wait(1).to({x:114.9},0).wait(1).to({x:97.65},0).wait(1).to({x:80.45},0).wait(1).to({x:63.2},0).wait(1).to({x:45.95},0).wait(1).to({x:28.7},0).wait(1).to({x:11.45},0).wait(1).to({x:-5.8},0).wait(1).to({x:-23},0).wait(1).to({x:-40.25},0).wait(1).to({x:-57.5},0).wait(1).to({x:-74.75},0).wait(11));

	// ReedsandLake_Midground_copy
	this.reedsAndLake = new lib.reedsAndLake();
	this.reedsAndLake.name = "reedsAndLake";
	this.reedsAndLake.setTransform(345.25,159.05,1,1,0,0,0,0.5,0);

	this.timeline.addTween(cjs.Tween.get(this.reedsAndLake).wait(1).to({regX:4.8,regY:-73.7,x:349.55,y:85.75},0).wait(1).to({y:86.2},0).wait(1).to({y:86.65},0).wait(1).to({y:87.1},0).wait(1).to({y:87.55},0).wait(1).to({y:88},0).wait(1).to({y:88.45},0).wait(1).to({y:88.9},0).wait(1).to({y:89.35},0).wait(1).to({y:89.8},0).wait(1).to({y:90.25},0).wait(1).to({y:90.7},0).wait(1).to({y:91.1},0).wait(1).to({y:91.55},0).wait(1).to({y:92},0).wait(1).to({y:92.45},0).wait(1).to({y:92.9},0).wait(1).to({y:93.35},0).wait(1).to({y:93.8},0).wait(1).to({y:94.25},0).wait(1).to({y:94.7},0).wait(1).to({y:95.15},0).wait(1).to({y:95.6},0).wait(1).to({x:349.6,y:96.05},0).wait(1).to({y:96},0).wait(7).to({y:95.95},0).wait(7).to({y:95.9},0).wait(8).to({y:95.85},0).wait(7).to({y:95.8},0).wait(8).to({y:95.75},0).wait(7).to({y:95.7},0).wait(7).to({y:95.65},0).wait(8).to({y:95.6},0).wait(7).to({y:95.55},0).wait(66));

	// Forest
	this.forest = new lib.forest();
	this.forest.name = "forest";
	this.forest.setTransform(350.55,151.7,1,1,0,0,0,373.7,81);

	this.timeline.addTween(cjs.Tween.get(this.forest).wait(1).to({regX:-43.3,regY:-152.4,x:-66.45,y:-81.45},0).wait(1).to({y:-81.2},0).wait(1).to({y:-80.95},0).wait(1).to({y:-80.65},0).wait(1).to({y:-80.4},0).wait(1).to({y:-80.15},0).wait(1).to({y:-79.9},0).wait(1).to({y:-79.6},0).wait(1).to({y:-79.35},0).wait(1).to({y:-79.1},0).wait(1).to({y:-78.85},0).wait(1).to({y:-78.55},0).wait(1).to({y:-78.3},0).wait(1).to({y:-78.05},0).wait(1).to({y:-77.8},0).wait(1).to({y:-77.5},0).wait(1).to({y:-77.25},0).wait(1).to({y:-77},0).wait(1).to({y:-76.75},0).wait(1).to({y:-76.45},0).wait(1).to({y:-76.2},0).wait(1).to({y:-75.95},0).wait(1).to({y:-75.7},0).wait(1).to({y:-75.4},0).wait(133));

	// clouds
	this.clouds = new lib.clouds();
	this.clouds.name = "clouds";
	this.clouds.setTransform(351.6,47.95,0.3775,0.4846,0,0,0,244.6,12.5);

	this.timeline.addTween(cjs.Tween.get(this.clouds).wait(157));

	// skyBackground
	this.instance_3 = new lib.Background_Sky();
	this.instance_3.setTransform(350,100);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#330000").ss(1,1,1).p("Eg3agQ9MBu1AAAMAAAAh7Mhu1AAAg");
	this.shape.setTransform(349.875,102.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance_3}]}).wait(157));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-507.2,-296.2,1373.6,577.5999999999999);
// library properties:
lib.properties = {
	id: 'F3EBAA7B947E694CAA2D115335F7421E',
	width: 700,
	height: 200,
	fps: 24,
	color: "#33D4FF",
	opacity: 1.00,
	manifest: [
		{src:"images/cryptids33_atlas_1.png?1773962939330", id:"cryptids33_atlas_1"},
		{src:"images/cryptids33_atlas_2.png?1773962939330", id:"cryptids33_atlas_2"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['F3EBAA7B947E694CAA2D115335F7421E'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;